'use client';
import{FormEvent,TouchEvent,useEffect,useRef,useState}from'react';
import{createBrowserSupabase}from'@/lib/supabase/client';
import{KonkiLogo}from'./brand';
import{friendlyError}from'@/lib/product-utils';
const supabase=createBrowserSupabase();
type Mode='welcome'|'parent-intro'|'youth-intro'|'login'|'signup-choice'|'parent-signup'|'youth-signup'|'forgot'|'oauth-profile';
type ApiResponse={error?:string;loginEmail?:string};
type IntroRole='parent'|'youth';
const intros={parent:[['Pare de simplesmente dar. Ensine a conquistar.','Seu filho escolhe algo que realmente deseja. A KONKI transforma esse objetivo em uma jornada de desenvolvimento.'],['A KONKI prepara o caminho.','Missões de autonomia, dinheiro, comunicação, disciplina e tomada de decisão são adaptadas à idade e à conquista.'],['Você acompanha o que realmente importa.','Veja o que ele fez, o que aprendeu, as evidências enviadas e como está evoluindo. Você aprova o progresso.'],['No final, não é só sobre o prêmio.','Ele conquista aquilo que queria e constrói um histórico do que foi capaz de fazer para chegar lá.']],youth:[['O que você quer conquistar?','Um tênis? Uma viagem? Um videogame? Um projeto seu? Você escolhe.'],['A KONKI monta seu caminho.','Você recebe missões para provar que consegue chegar lá. Nada de ficar só pedindo.'],['Cada missão te aproxima.','Complete desafios, envie suas provas e veja sua conquista sair de 0% até 100%.'],['Chegue aos 100%. Conquiste.','Mostre que você fez por merecer e construa seu histórico de conquistas.']]} as const;
function initialEntry(){if(typeof window==='undefined')return{mode:'welcome' as Mode,step:0};const query=new URLSearchParams(location.search),auth=query.get('auth'),intro=query.get('intro'),signup=query.get('signup');if(signup==='youth'||auth==='youth-signup')return{mode:'youth-signup' as Mode,step:0};if(signup==='parent')return{mode:'parent-signup' as Mode,step:0};if(auth&&['welcome','login','signup-choice','parent-signup','forgot'].includes(auth))return{mode:auth as Mode,step:0};if(intro==='parent'||intro==='youth')return{mode:`${intro}-intro` as Mode,step:Math.min(3,Math.max(0,Number(query.get('step')||1)-1))};return{mode:'welcome' as Mode,step:0}}
function Message({children,ok=false}:{children:string;ok?:boolean}){return <div className={`notice ${ok?'success':''}`} role="status">{children}</div>}
export default function AuthScreen(){
 const linkInvite=typeof window!=='undefined'&&new URLSearchParams(location.search).get('invite')==='1';
 const initial=initialEntry(),[mode,setMode]=useState<Mode>(initial.mode),[introStep,setIntroStep]=useState(initial.step),[message,setMessage]=useState(''),[ok,setOk]=useState(false),[busy,setBusy]=useState(false),[oauthRole,setOauthRole]=useState<'PARENT'|'YOUTH'>('PARENT');
 useEffect(()=>{supabase.auth.getSession().then(async({data})=>{if(!data.session)return;const member=await supabase.from('family_members').select('family_id').eq('profile_id',data.session.user.id).maybeSingle();if(!member.data){const inviteRole=new URLSearchParams(location.search).get('inviteRole');if(inviteRole==='parent'||inviteRole==='youth')setOauthRole(inviteRole==='parent'?'PARENT':'YOUTH');setMode('oauth-profile')}})},[]);
 useEffect(()=>{const restore=()=>{const next=initialEntry();setMode(next.mode);setIntroStep(next.step)};addEventListener('popstate',restore);return()=>removeEventListener('popstate',restore)},[]);
 const route=(next:Mode,step=0,replace=false)=>{const url=new URL(location.href);url.searchParams.delete('auth');url.searchParams.delete('intro');url.searchParams.delete('step');if(next==='parent-intro'||next==='youth-intro'){url.searchParams.set('intro',next.startsWith('parent')?'parent':'youth');url.searchParams.set('step',String(step+1))}else if(next!=='welcome')url.searchParams.set('auth',next);history[replace?'replaceState':'pushState'](null,'',url.pathname+url.search);setMode(next);setIntroStep(step);setMessage('');setOk(false)};
 const change=(next:Mode)=>{if(['login','signup-choice','parent-signup','youth-signup'].includes(next))localStorage.setItem('konki-entry-seen','1');route(next)};
 // Mantido para ativação pós-MVP; não é exposto na interface atual.
 // eslint-disable-next-line @typescript-eslint/no-unused-vars
 const oauth=async(provider:'google'|'apple')=>{setMessage('');setBusy(true);const{error}=await supabase.auth.signInWithOAuth({provider,options:{redirectTo:`${location.origin}/auth/callback`}});if(error){setBusy(false);setMessage('Não foi possível iniciar esse acesso. O provedor pode ainda não estar configurado.')}};
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setMessage('');setOk(false);const f=new FormData(e.currentTarget);try{
  if(mode==='login'){localStorage.setItem('konki-entry-seen','1');const{error}=await supabase.auth.signInWithPassword({email:String(f.get('email')),password:String(f.get('password'))});if(error)throw new Error('E-mail ou senha inválidos.')}
  if(mode==='forgot'){const{error}=await supabase.auth.resetPasswordForEmail(String(f.get('email')),{redirectTo:`${location.origin}/auth/reset`});if(error)throw new Error('Não foi possível enviar o link agora. Tente novamente.');setOk(true);setMessage('Se esse e-mail estiver cadastrado, você receberá um link para criar uma nova senha.')}
  if(mode==='parent-signup'){const response=await fetch(linkInvite?'/api/auth/register-invited-parent':'/api/auth/register-parent',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({firstName:f.get('firstName'),lastName:f.get('lastName'),email:f.get('email'),password:f.get('password'),familyName:f.get('familyName'),youthName:f.get('youthName'),youthAge:Number(f.get('youthAge')),relationship:f.get('relationship')})});const body=await response.json() as ApiResponse;if(!response.ok)throw new Error(body.error||'Não foi possível criar a conta.');const{error}=await supabase.auth.signInWithPassword({email:String(f.get('email')),password:String(f.get('password'))});if(error)throw error}
  if(mode==='youth-signup'){const rawCode=f.get('code');const response=await fetch('/api/auth/register-youth',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({code:rawCode?String(rawCode).toUpperCase():'',firstName:f.get('firstName'),username:f.get('username'),password:f.get('password')})});const body=await response.json() as ApiResponse;if(!response.ok||!body.loginEmail)throw new Error(body.error||'Não foi possível criar a conta.');const{error}=await supabase.auth.signInWithPassword({email:body.loginEmail,password:String(f.get('password'))});if(error)throw error}
  if(mode==='oauth-profile'){const{data}=await supabase.auth.getSession();const response=await fetch(linkInvite?'/api/auth/invite-link':'/api/auth/complete-oauth-profile',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${data.session?.access_token}`},body:JSON.stringify({role:oauthRole,firstName:f.get('firstName'),familyName:f.get('familyName'),inviteCode:String(f.get('inviteCode')||'').toUpperCase(),birthDate:f.get('birthDate')||null})});const body=await response.json() as ApiResponse;if(!response.ok)throw new Error(body.error||'Não foi possível concluir o perfil.');location.assign('/')}
 }catch(error){setMessage(friendlyError(error,'Não foi possível continuar. Confira os dados e tente novamente.'))}finally{setBusy(false)}};
 if(mode==='welcome')return <EntryWelcome onRole={role=>{if(linkInvite){const url=new URL(location.href);url.searchParams.set('inviteRole',role);history.replaceState(null,'',url.pathname+url.search)}route(`${role}-intro`,0)}} onLogin={()=>change('login')}/>;
 if(mode==='parent-intro'||mode==='youth-intro'){const role:IntroRole=mode.startsWith('parent')?'parent':'youth';return <EntryTour role={role} step={introStep} onStep={step=>route(mode,step)} onBack={()=>introStep?route(mode,introStep-1):route('welcome')} onSkip={()=>change(role==='parent'?'parent-signup':'youth-signup')} onLogin={()=>change('login')} onFinish={()=>change(role==='parent'?'parent-signup':'youth-signup')}/>}
 if(mode==='oauth-profile')return <main className="auth-page"><section className="auth-card"><KonkiLogo/><h1>{linkInvite?'Entrar na família':'Como você vai usar a KONKI?'}</h1><div className="profile-choice"><button className={oauthRole==='PARENT'?'selected':''} onClick={()=>setOauthRole('PARENT')}><b>Sou responsável</b><small>Acompanhar e ajudar o jovem.</small></button><button className={oauthRole==='YOUTH'?'selected':''} onClick={()=>setOauthRole('YOUTH')}><b>Sou jovem</b><small>Começar minha jornada de conquistas.</small></button></div>{message&&<Message>{message}</Message>}<form className="form-stack" onSubmit={submit}><label>Como quer ser chamado?<input name="firstName" required minLength={2}/></label>{oauthRole==='PARENT'?(!linkInvite&&<label>Nome da família<input name="familyName" placeholder="Minha família"/></label>):<>{!linkInvite&&<label>Código do convite<input name="inviteCode" minLength={6} maxLength={6} required/></label>}<label>Data de nascimento<input name="birthDate" type="date" lang="pt-BR" required/></label></>}<button className="primary" disabled={busy}>{busy?'Salvando…':'Continuar'}</button></form></section></main>;
 if(mode==='signup-choice')return <main className="auth-page"><section className="auth-card"><button className="back" onClick={()=>change('login')}>‹ Voltar</button><KonkiLogo/><h1>Criar conta</h1><p>Como você vai usar a KONKI?</p><div className="profile-choice"><button onClick={()=>change('parent-signup')}><b>Sou responsável</b><small>Acompanhar e ajudar um jovem.</small></button><button onClick={()=>change('youth-signup')}><b>Sou jovem</b><small>Tenho um convite da minha família.</small></button></div></section></main>;
 if(mode==='login')return <main className="auth-page login-final"><section className="auth-card login-card"><KonkiLogo/><p className="login-tagline">Aprenda a conquistar.</p>{message&&<Message>{message}</Message>}<form className="form-stack" onSubmit={submit}><label>E-mail<input name="email" type="email" autoComplete="email" required/></label><label>Senha<input name="password" type="password" minLength={8} autoComplete="current-password" required/></label><button className="primary" disabled={busy}>{busy?'Entrando…':'Entrar'}</button></form><button className="switch" onClick={()=>change('forgot')}>Esqueci minha senha</button><p className="signup-line">Ainda não tem conta? <button onClick={()=>change('signup-choice')}>Criar conta</button></p></section></main>;
 return <main className="auth-page"><section className="auth-card"><button className="back" onClick={()=>change(mode==='forgot'?'login':'signup-choice')}>‹ Voltar</button><KonkiLogo/><h1>{mode==='forgot'?'Recuperar senha':linkInvite?'Entrar na família':'Comece sua jornada'}</h1><p>{mode==='forgot'?'Informe seu e-mail para receber o link.':mode==='youth-signup'?(linkInvite?'Seu convite já está pronto. Crie sua conta para entrar na família.':'Use o convite da sua família.'):linkInvite?'Crie sua conta de responsável para entrar nesta família.':'Crie o espaço privado da sua família.'}</p>{message&&<Message ok={ok}>{message}</Message>}<form className="form-stack" onSubmit={submit}>{mode==='parent-signup'&&<><div className="form-row"><label>Seu nome<input name="firstName" required/></label><label>Sobrenome<input name="lastName" required/></label></div>{!linkInvite&&<><label>Nome da família<input name="familyName" defaultValue="Minha família" required/></label><label>Nome do jovem<input name="youthName" required/></label><div className="form-row"><label>Idade atual<input name="youthAge" type="number" min="8" max="21" required/></label><label>Relação<select name="relationship"><option>Mãe</option><option>Pai</option><option>Responsável</option></select></label></div></>}</>}{mode==='youth-signup'&&<>{!linkInvite&&<label>Código do convite<input name="code" minLength={6} maxLength={6} required/></label>}<label>Seu nome<input name="firstName" required/></label><label>Nome de usuário<input name="username" minLength={3} required/></label></>}{mode!=='youth-signup'&&<label>E-mail<input name="email" type="email" autoComplete="email" required/></label>}{mode!=='forgot'&&<label>Senha<input name="password" type="password" minLength={8} required/></label>}<button className="primary" disabled={busy}>{busy?'Aguarde…':mode==='forgot'?'Enviar link':linkInvite?'Entrar na família':'Continuar'}</button></form></section></main>;
}

function EntryWelcome({onRole,onLogin}:{onRole:(role:IntroRole)=>void;onLogin:()=>void}){return <main className="entry-page"><section className="entry-shell"><header className="entry-brand"><KonkiLogo/></header><div className="entry-hero"><span className="eyebrow">ESCOLHA. ESFORÇO. PROGRESSO.</span><h1>Transforme objetivos em conquistas.</h1><p>A KONKI ajuda jovens a conquistarem o que desejam através de esforço, aprendizado e desenvolvimento.</p></div><div className="entry-roles"><button onClick={()=>onRole('parent')}><b>Sou responsável</b><small>Quero ajudar meu filho a aprender a conquistar.</small><i aria-hidden="true">→</i></button><button onClick={()=>onRole('youth')}><b>Sou jovem</b><small>Quero conquistar algo que eu quero.</small><i aria-hidden="true">→</i></button></div><button className="entry-login" onClick={onLogin}>Já tenho conta <span>→ Entrar</span></button></section></main>}

function EntryTour({role,step,onStep,onBack,onSkip,onLogin,onFinish}:{role:IntroRole;step:number;onStep:(step:number)=>void;onBack:()=>void;onSkip:()=>void;onLogin:()=>void;onFinish:()=>void}){const cards=intros[role],card=cards[step],touchStart=useRef(0);const touchBegin=(event:TouchEvent)=>{touchStart.current=event.changedTouches[0].clientX};const touchEnd=(event:TouchEvent)=>{const distance=event.changedTouches[0].clientX-touchStart.current;if(Math.abs(distance)<45)return;if(distance<0&&step<3)onStep(step+1);if(distance>0)onBack()};return <main className="entry-page"><section className="entry-shell entry-tour"><header className="entry-tour-head"><button onClick={onBack} aria-label="Voltar">←</button><KonkiLogo/><button onClick={onSkip}>Pular</button></header><div className="entry-progress" aria-label={`Etapa ${step+1} de 4`}><span>{step+1}/4</span><div>{cards.map((_,index)=><i key={index} className={index<=step?'active':''}/>)}</div></div><article className="entry-story" onTouchStart={touchBegin} onTouchEnd={touchEnd}><span>{role==='parent'?'PARA RESPONSÁVEIS':'PARA JOVENS'}</span><h1>{card[0]}</h1><p>{card[1]}</p></article><footer className="entry-tour-actions">{step<3?<><button className="primary" onClick={()=>onStep(step+1)}>Continuar</button><button className="entry-login" onClick={onLogin}>Já tenho conta <span>→ Entrar</span></button></>:<><button className="primary" onClick={onFinish}>{role==='parent'?'Criar minha família':'Começar minha primeira conquista'}</button><button className="entry-login" onClick={onLogin}>Já tenho conta <span>→ Entrar</span></button></>}</footer></section></main>}
