'use client';
import{FormEvent,useEffect,useState}from'react';
import{createBrowserSupabase}from'@/lib/supabase/client';
import{KonkiLogo}from'./brand';
import{friendlyError}from'@/lib/product-utils';
const supabase=createBrowserSupabase();
type Mode='login'|'signup-choice'|'parent-signup'|'youth-signup'|'forgot'|'oauth-profile';
function Message({children,ok=false}:{children:string;ok?:boolean}){return <div className={`notice ${ok?'success':''}`} role="status">{children}</div>}
export default function AuthScreen(){
 const linkInvite=typeof window!=='undefined'&&new URLSearchParams(location.search).get('invite')==='1';
 const[mode,setMode]=useState<Mode>(()=>typeof window!=='undefined'&&new URLSearchParams(location.search).get('signup')==='youth'?'youth-signup':'login'),[message,setMessage]=useState(''),[ok,setOk]=useState(false),[busy,setBusy]=useState(false),[oauthRole,setOauthRole]=useState<'PARENT'|'YOUTH'>('PARENT');
 useEffect(()=>{supabase.auth.getSession().then(async({data})=>{if(!data.session)return;const member=await supabase.from('family_members').select('family_id').eq('profile_id',data.session.user.id).maybeSingle();if(!member.data)setMode('oauth-profile')})},[]);
 const change=(next:Mode)=>{setMode(next);setMessage('');setOk(false)};
 // Mantido para ativação pós-MVP; não é exposto na interface atual.
 // eslint-disable-next-line @typescript-eslint/no-unused-vars
 const oauth=async(provider:'google'|'apple')=>{setMessage('');setBusy(true);const{error}=await supabase.auth.signInWithOAuth({provider,options:{redirectTo:`${location.origin}/auth/callback`}});if(error){setBusy(false);setMessage('Não foi possível iniciar esse acesso. O provedor pode ainda não estar configurado.')}};
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setMessage('');setOk(false);const f=new FormData(e.currentTarget);try{
  if(mode==='login'){const{error}=await supabase.auth.signInWithPassword({email:String(f.get('email')),password:String(f.get('password'))});if(error)throw new Error('E-mail ou senha inválidos.')}
  if(mode==='forgot'){const{error}=await supabase.auth.resetPasswordForEmail(String(f.get('email')),{redirectTo:`${location.origin}/auth/reset`});if(error)throw new Error('Não foi possível enviar o link agora. Tente novamente.');setOk(true);setMessage('Se esse e-mail estiver cadastrado, você receberá um link para criar uma nova senha.')}
  if(mode==='parent-signup'){const response=await fetch('/api/auth/register-parent',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({firstName:f.get('firstName'),lastName:f.get('lastName'),email:f.get('email'),password:f.get('password'),familyName:f.get('familyName'),youthName:f.get('youthName'),youthAge:Number(f.get('youthAge')),relationship:f.get('relationship')})});const body=await response.json();if(!response.ok)throw new Error(body.error);const{error}=await supabase.auth.signInWithPassword({email:String(f.get('email')),password:String(f.get('password'))});if(error)throw error}
  if(mode==='youth-signup'){const rawCode=f.get('code');const response=await fetch('/api/auth/register-youth',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({code:rawCode?String(rawCode).toUpperCase():'',firstName:f.get('firstName'),username:f.get('username'),password:f.get('password')})});const body=await response.json();if(!response.ok)throw new Error(body.error);const{error}=await supabase.auth.signInWithPassword({email:body.loginEmail,password:String(f.get('password'))});if(error)throw error}
  if(mode==='oauth-profile'){const{data}=await supabase.auth.getSession();const response=await fetch('/api/auth/complete-oauth-profile',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${data.session?.access_token}`},body:JSON.stringify({role:oauthRole,firstName:f.get('firstName'),familyName:f.get('familyName'),inviteCode:String(f.get('inviteCode')||'').toUpperCase(),birthDate:f.get('birthDate')||null})});const body=await response.json();if(!response.ok)throw new Error(body.error);location.assign('/')}
 }catch(error){setMessage(friendlyError(error,'Não foi possível continuar. Confira os dados e tente novamente.'))}finally{setBusy(false)}};
 if(mode==='oauth-profile')return <main className="auth-page"><section className="auth-card"><KonkiLogo/><h1>Como você vai usar a KONKI?</h1><div className="profile-choice"><button className={oauthRole==='PARENT'?'selected':''} onClick={()=>setOauthRole('PARENT')}><b>Sou responsável</b><small>Acompanhar e ajudar um jovem.</small></button><button className={oauthRole==='YOUTH'?'selected':''} onClick={()=>setOauthRole('YOUTH')}><b>Sou jovem</b><small>Entrar na minha família e começar.</small></button></div>{message&&<Message>{message}</Message>}<form className="form-stack" onSubmit={submit}><label>Como quer ser chamado?<input name="firstName" required minLength={2}/></label>{oauthRole==='PARENT'?<label>Nome da família<input name="familyName" placeholder="Minha família"/></label>:<><label>Código do convite<input name="inviteCode" minLength={6} maxLength={6} required/></label><label>Data de nascimento<input name="birthDate" type="date" lang="pt-BR" required/></label></>}<button className="primary" disabled={busy}>{busy?'Salvando…':'Continuar'}</button></form></section></main>;
 if(mode==='signup-choice')return <main className="auth-page"><section className="auth-card"><button className="back" onClick={()=>change('login')}>‹ Voltar</button><KonkiLogo/><h1>Criar conta</h1><p>Como você vai usar a KONKI?</p><div className="profile-choice"><button onClick={()=>change('parent-signup')}><b>Sou responsável</b><small>Acompanhar e ajudar um jovem.</small></button><button onClick={()=>change('youth-signup')}><b>Sou jovem</b><small>Tenho um convite da minha família.</small></button></div></section></main>;
 if(mode==='login')return <main className="auth-page login-final"><section className="auth-card login-card"><KonkiLogo/><p className="login-tagline">Aprenda a conquistar.</p>{message&&<Message>{message}</Message>}<form className="form-stack" onSubmit={submit}><label>E-mail<input name="email" type="email" autoComplete="email" required/></label><label>Senha<input name="password" type="password" minLength={8} autoComplete="current-password" required/></label><button className="primary" disabled={busy}>{busy?'Entrando…':'Entrar'}</button></form><button className="switch" onClick={()=>change('forgot')}>Esqueci minha senha</button><p className="signup-line">Ainda não tem conta? <button onClick={()=>change('signup-choice')}>Criar conta</button></p></section></main>;
 return <main className="auth-page"><section className="auth-card"><button className="back" onClick={()=>change(mode==='forgot'?'login':'signup-choice')}>‹ Voltar</button><KonkiLogo/><h1>{mode==='forgot'?'Recuperar senha':'Comece sua jornada'}</h1><p>{mode==='forgot'?'Informe seu e-mail para receber o link.':mode==='youth-signup'?(linkInvite?'Seu convite já está pronto. Crie sua conta para entrar na família.':'Use o convite da sua família.'):'Crie o espaço privado da sua família.'}</p>{message&&<Message ok={ok}>{message}</Message>}<form className="form-stack" onSubmit={submit}>{mode==='parent-signup'&&<><div className="form-row"><label>Seu nome<input name="firstName" required/></label><label>Sobrenome<input name="lastName" required/></label></div><label>Nome da família<input name="familyName" defaultValue="Minha família" required/></label><label>Nome do jovem<input name="youthName" required/></label><div className="form-row"><label>Idade atual<input name="youthAge" type="number" min="8" max="21" required/></label><label>Relação<select name="relationship"><option>Mãe</option><option>Pai</option><option>Responsável</option></select></label></div></>}{mode==='youth-signup'&&<>{!linkInvite&&<label>Código do convite<input name="code" minLength={6} maxLength={6} required/></label>}<label>Seu nome<input name="firstName" required/></label><label>Nome de usuário<input name="username" minLength={3} required/></label></>}{mode!=='youth-signup'&&<label>E-mail<input name="email" type="email" autoComplete="email" required/></label>}{mode!=='forgot'&&<label>Senha<input name="password" type="password" minLength={8} required/></label>}<button className="primary" disabled={busy}>{busy?'Aguarde…':mode==='forgot'?'Enviar link':'Continuar'}</button></form></section></main>;
}
