'use client';
/* eslint-disable @typescript-eslint/no-unused-vars */

import {FormEvent,useCallback,useEffect,useMemo,useState} from 'react';
import type {Session} from '@supabase/supabase-js';
import {createBrowserSupabase} from '@/lib/supabase/client';
import ThemeControl from './theme-control';
import AuthScreen from './auth-screen';
import {KonkiLogo,KonkiMark} from './brand';
import {ageGuidance,formatBrazilianDateInput,friendlyError,getBirthdayState,moneyBRL,onboardingIsComplete,parseBrazilianBirthDate} from '@/lib/product-utils';
import {appRouteUrl,notificationRoute,parseAppRoute,type AppRoute,type AppView} from '@/lib/app-navigation';
import {evidenceLabel,roleLabel,skillLabel,statusLabel} from '@/lib/presentation-labels';

type Role='PARENT'|'YOUTH'|'ADMIN';
type View=AppView;
type Go=(view:View,params?:Pick<AppRoute,'assignmentId'|'contractId'|'journeyId'>)=>void;
type Profile={id:string;role:Role;first_name:string;last_name?:string;username?:string};
type Family={id:string;name:string;invite_code:string};
type Mission={id:string;title:string;description:string;category:string;skills:string[];difficulty:string;estimated_minutes:number;xp_reward:number;goal_progress_reward:number;evidence_types:string[];lesson_title:string;lesson_content:Record<string,unknown>};
type Assignment={id:string;status:string;recommendation_reasons:string[];mission:Mission;conquest_id:string;journey_id?:string|null;mission_order?:number|null;started_at?:string|null};
type ApiResponse={error?:string;inviteCode?:string;loginEmail?:string;missionCount?:number;suggestedWeeks?:number;[key:string]:unknown};

const supabase=createBrowserSupabase();
const labels:Record<string,string>={EASY:'Fácil',MEDIUM:'Média',HARD:'Desafiadora',LOCKED:'Bloqueada',AVAILABLE:'Disponível',STARTED:'Em andamento',SUBMITTED:'Aguardando revisão',APPROVED:'Aprovada',NEEDS_CHANGES:'Precisa de ajuste'};
const skills=['Responsabilidade','Autonomia','Educação financeira','Comunicação','Disciplina','Organização','Iniciativa','Empreendedorismo','Tomada de decisão','Pensamento crítico'];
const interests=['Tecnologia','Esportes','Música','Games','Culinária','Arte','Animais','Vídeos'];

function Mark(){return <KonkiMark/>}
function Logo(){return <KonkiLogo/>}
function Progress({value}:{value:number}){return <div className="progress-track"><span style={{width:`${Math.min(100,value)}%`}}/></div>}
function Alert({kind='error',children}:{kind?:'error'|'success';children:React.ReactNode}){return <div className={`notice ${kind}`}>{children}</div>}
function Busy(){return <main className="splash"><Logo/><span>Preparando sua jornada</span></main>}
function RetryState({message,onRetry}:{message:string;onRetry:()=>void}){return <section className="empty-card" role="alert"><h2>Não foi possível carregar</h2><p>{message}</p><button className="secondary wide" onClick={onRetry}>Tentar novamente</button></section>}
function LoadingState({label='Carregando…'}:{label?:string}){return <section className="empty-card async-loading" aria-live="polite"><p>{label}</p></section>}

export default function FunctionalApp({initialView}:{initialView?:View}){
  const initialRoute=()=>typeof window==='undefined'?{view:initialView||'home'}:parseAppRoute(window.location.href,initialView||'home');
  const[session,setSession]=useState<Session|null>(null),[loading,setLoading]=useState(true),[bootError,setBootError]=useState(''),[profile,setProfile]=useState<Profile|null>(null),[family,setFamily]=useState<Family|null>(null),[onboardingComplete,setOnboardingComplete]=useState<boolean|null>(null),[route,setRoute]=useState<AppRoute>(initialRoute),[refresh,setRefresh]=useState(0);
  const view=route.view;
  const reload=()=>setRefresh(x=>x+1);
  const go:Go=useCallback((next,params={})=>{const nextRoute={view:next,...params};history.pushState(null,'',appRouteUrl(nextRoute));setRoute(nextRoute)},[]);
  const load=useCallback(async(s:Session|null)=>{setLoading(true);setBootError('');setSession(s);if(!s){setProfile(null);setFamily(null);setOnboardingComplete(null);setLoading(false);return}try{const p=await supabase.from('profiles').select('*').eq('id',s.user.id).single();if(p.error)throw p.error;const nextProfile=p.data as Profile;const fm=await supabase.from('family_members').select('families(id,name,invite_code)').eq('profile_id',s.user.id).limit(1).maybeSingle();if(fm.error)throw fm.error;let complete=true;if(nextProfile.role!=='ADMIN'){const table=nextProfile.role==='YOUTH'?'youth_profiles':'parent_profiles';const fields=nextProfile.role==='YOUTH'?'onboarding_completed_at,birth_date':'onboarding_completed_at';const state=await supabase.from(table).select(fields).eq('profile_id',s.user.id).maybeSingle();if(state.error)throw state.error;complete=onboardingIsComplete(nextProfile.role,state.data as {onboarding_completed_at?:string|null;birth_date?:string|null}|null);try{const key=`konki-onboarding-${nextProfile.id}`;if(complete)localStorage.setItem(key,'1');else localStorage.removeItem(key)}catch{}}setProfile(nextProfile);setFamily((fm.data?.families as unknown as Family)||null);setOnboardingComplete(complete)}catch{setBootError('Não conseguimos carregar seu perfil com segurança. Sua sessão foi mantida.')}finally{setLoading(false)}},[]);
  useEffect(()=>{supabase.auth.getSession().then(({data})=>load(data.session));const{data}=supabase.auth.onAuthStateChange((_e,s)=>load(s));return()=>data.subscription.unsubscribe()},[load,refresh]);
  useEffect(()=>{const pop=()=>setRoute(parseAppRoute(location.href,initialView||'home'));addEventListener('popstate',pop);return()=>removeEventListener('popstate',pop)},[initialView]);
  useEffect(()=>{if(!session)return;const canonical=appRouteUrl(route);if(location.pathname+location.search!==canonical)history.replaceState(null,'',canonical)},[route,session]);
  if(loading)return <Busy/>;
  if(bootError)return <main className="auth-page"><RetryState message={bootError} onRetry={reload}/></main>;
  if(!session||!profile||(!family&&profile.role!=='ADMIN'))return <AuthScreen/>;
  const mustOnboard=profile.role!=='ADMIN'&&!onboardingComplete;
  const logout=async()=>{await supabase.auth.signOut()};
  return <main className="app-shell"><header className="topbar"><Logo/><div className="top-actions"><button className="icon-button" onClick={()=>go('notifications')} aria-label="Notificações">●</button><button className="avatar" onClick={()=>go('profile')}>{profile.first_name.slice(0,1)}{profile.last_name?.slice(0,1)||''}</button></div></header><div className="content">
    {mustOnboard&&<Onboarding profile={profile} family={family} done={()=>{go('home');reload()}}/>}
    {!mustOnboard&&view==='home'&&<Dashboard profile={profile} family={family} go={go}/>} 
    {!mustOnboard&&view==='conquest'&&<Conquest profile={profile} family={family} go={go}/>} 
    {!mustOnboard&&view==='wishlist'&&<PilotWishlist profile={profile} family={family} go={go}/>} 
    {!mustOnboard&&view==='archive'&&<PilotArchive go={go}/>} 
    {!mustOnboard&&view==='journey-review'&&<JourneyReview go={go} journeyId={route.journeyId}/>}
    {!mustOnboard&&view==='missions'&&<Missions go={go}/>} 
    {!mustOnboard&&view==='mission'&&<MissionFlow go={go} assignmentId={route.assignmentId}/>} 
    {!mustOnboard&&view==='review'&&<PilotReview assignmentId={route.assignmentId}/>} 
    {!mustOnboard&&view==='contract'&&<PilotContract profile={profile} contractId={route.contractId}/>} 
    {!mustOnboard&&view==='notifications'&&<PilotNotifications go={go}/>} 
    {!mustOnboard&&view==='passport'&&<Passport profile={profile}/>} 
    {!mustOnboard&&view==='profile'&&<ProfileScreen profile={profile} family={family} logout={logout}/>} 
    {!mustOnboard&&view==='admin'&&<Admin/>}
  </div>{!mustOnboard&&<Nav role={profile.role} active={view} go={go}/>}</main>
}

function Auth(){
  const[mode,setMode]=useState<'landing'|'parent-login'|'parent-signup'|'youth-login'|'youth-signup'>('landing'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[invite,setInvite]=useState('');
  const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setError('');setBusy(true);const f=new FormData(e.currentTarget);try{
    if(mode==='parent-login'){const{error}=await supabase.auth.signInWithPassword({email:String(f.get('email')),password:String(f.get('password'))});if(error)throw error}
    if(mode==='parent-signup'){const r=await fetch('/api/auth/register-parent',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({firstName:f.get('firstName'),lastName:f.get('lastName'),email:f.get('email'),password:f.get('password'),familyName:f.get('familyName'),youthName:f.get('youthName'),youthAge:Number(f.get('youthAge')),relationship:f.get('relationship')})});const j=await r.json() as ApiResponse;if(!r.ok)throw new Error(j.error||'Não foi possível criar a conta.');if(j.inviteCode)setInvite(j.inviteCode);const{error}=await supabase.auth.signInWithPassword({email:String(f.get('email')),password:String(f.get('password'))});if(error)throw error}
    if(mode==='youth-signup'){const r=await fetch('/api/auth/register-youth',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({code:String(f.get('code')).toUpperCase(),firstName:f.get('firstName'),username:f.get('username'),password:f.get('password')})});const j=await r.json() as ApiResponse;if(!r.ok||!j.loginEmail)throw new Error(j.error||'Não foi possível criar a conta.');localStorage.setItem('konki-youth-code',String(f.get('code')).toUpperCase());const{error}=await supabase.auth.signInWithPassword({email:j.loginEmail,password:String(f.get('password'))});if(error)throw error}
    if(mode==='youth-login'){const r=await fetch('/api/auth/resolve-youth',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username:f.get('username'),code:String(f.get('code')).toUpperCase()})});const j=await r.json() as ApiResponse;if(!r.ok||!j.loginEmail)throw new Error(j.error||'Não foi possível entrar.');const{error}=await supabase.auth.signInWithPassword({email:j.loginEmail,password:String(f.get('password'))});if(error)throw error}
  }catch(err){setError(err instanceof Error?err.message:'Não foi possível continuar.')}finally{setBusy(false)}};
  if(mode==='landing')return <main className="welcome-screen"><div><Logo/><h1>Você escolhe.<br/>Você conquista.</h1><p>Objetivos reais viram esforço, habilidades e progresso que a família consegue acompanhar.</p></div><div className="welcome-path"><span>ESCOLHA</span><i/><span>ESFORÇO</span><i/><span>PROGRESSO</span><i/><span>CONQUISTA</span></div><div className="welcome-actions"><button className="primary" onClick={()=>setMode('youth-login')}>Entrar como jovem</button><button className="secondary" onClick={()=>setMode('parent-login')}>Entrar como responsável</button><button className="text-button" onClick={()=>setMode('parent-signup')}>Criar uma família</button><button className="text-button" onClick={()=>setMode('youth-signup')}>Tenho um convite</button></div></main>;
  return <main className="auth-page"><section className="auth-card"><button className="back" onClick={()=>setMode('landing')}>‹ Voltar</button><Logo/><h1>{mode.includes('signup')?'Crie sua jornada':'Bem-vindo de volta'}</h1><p>{mode.startsWith('parent')?'Área do responsável':'Área do jovem'}</p>{invite&&<Alert kind="success">Convite criado: <strong>{invite}</strong>. Compartilhe com o jovem.</Alert>}{error&&<Alert>{error}</Alert>}<form onSubmit={submit} className="form-stack">
    {mode==='parent-signup'&&<><label>Seu nome<input name="firstName" required minLength={2}/></label><label>Sobrenome<input name="lastName"/></label><label>Nome da família<input name="familyName" required defaultValue="Família Silva"/></label><label>Nome do jovem<input name="youthName" required/></label><div className="form-row"><label>Idade<input name="youthAge" type="number" min="8" max="21" required/></label><label>Relação<select name="relationship"><option>Mãe</option><option>Pai</option><option>Responsável</option></select></label></div></>}
    {mode==='youth-signup'&&<><label>Código do convite<input name="code" required minLength={6} maxLength={6} autoCapitalize="characters"/></label><label>Seu nome<input name="firstName" required/></label><label>Username<input name="username" required minLength={3}/></label></>}
    {mode==='youth-login'&&<><label>Username<input name="username" required/></label><label>Código da família<input name="code" required minLength={6} maxLength={6}/></label></>}
    {mode.startsWith('parent')&&<label>E-mail<input name="email" type="email" required/></label>}
    <label>Senha<input name="password" type="password" required minLength={8}/></label><button className="primary" disabled={busy}>{busy?'Aguarde…':'Continuar'}</button></form><button className="switch" onClick={()=>setMode(mode.endsWith('login')?(mode.startsWith('parent')?'parent-signup':'youth-signup'):(mode.startsWith('parent')?'parent-login':'youth-login'))}>{mode.endsWith('login')?'Ainda não tenho conta':'Já tenho conta'}</button></section></main>
}

function Onboarding({profile,family,done}:{profile:Profile;family:Family|null;done:()=>void}){
  const[step,setStep]=useState(0),[chosen,setChosen]=useState<string[]>([]),[error,setError]=useState(''),[showOther,setShowOther]=useState(false),[other,setOther]=useState(''),[birthDateInput,setBirthDateInput]=useState('');const youth=profile.role==='YOUTH';const options=youth?interests:skills;const birthDate=parseBrazilianBirthDate(birthDateInput);
  const addOther=()=>{const value=other.trim();if(value&&!chosen.some(x=>x.toLowerCase()===value.toLowerCase()))setChosen(v=>[...v,value]);setOther('')};
  const finish=async()=>{setError('');const table=youth?'youth_profiles':'parent_profiles';const data=youth?{interests:chosen,birth_date:birthDate,onboarding_completed_at:new Date().toISOString()}:{development_goals:chosen,current_challenges:['Rotina e consistência'],autonomy_level:'BALANCED',weekly_time_minutes:30,success_definition:'Mais autonomia na vida real',onboarding_completed_at:new Date().toISOString()};const{error}=await supabase.from(table).update(data).eq('profile_id',profile.id);if(error)setError(friendlyError(error,'Não foi possível salvar seu perfil. Tente novamente.'));else done()};
  return <section className="onboarding"><span className="eyebrow">PASSO {step+1} DE 3</span><Progress value={(step+1)*33}/>{step===0&&<><h1>Olá, {profile.first_name}.</h1><p>{youth?'Vamos descobrir o que combina com você.':'Vamos alinhar desenvolvimento, rotina e autonomia.'}</p><div className="family-badge"><Mark/><span><b>{family?.name}</b><small>Ambiente privado da sua família</small></span></div>{youth&&<div className="panel dob-field"><label>Sua data de nascimento<input value={birthDateInput} inputMode="numeric" autoComplete="bday" placeholder="DD / MM / AAAA" maxLength={14} required onChange={e=>setBirthDateInput(formatBrazilianDateInput(e.target.value))}/></label><small>Digite dia, mês e ano. Usamos a data para adaptar a linguagem e mostrar seu aniversário.</small>{birthDateInput.length===14&&!birthDate&&<span className="inline-error">Digite uma data válida que não esteja no futuro.</span>}{birthDate&&<b>{getBirthdayState(birthDate).age} anos hoje</b>}</div>}</>}{step===1&&<><h1>{youth?'Do que você curte?':'O que você mais gostaria que seu filho desenvolvesse?'}</h1><p>Escolha pelo menos duas opções. Isso orienta as recomendações.</p><div className="choice-grid">{options.map(x=><button key={x} className={chosen.includes(x)?'selected':''} onClick={()=>setChosen(v=>v.includes(x)?v.filter(i=>i!==x):[...v,x])}>{x}</button>)}<button className={showOther?'selected':''} onClick={()=>setShowOther(true)}>Outro</button></div>{showOther&&<div className="other-box"><label>{youth?'Conta pra gente do que você gosta.':'O que você gostaria que ele desenvolvesse?'}<input value={other} onChange={e=>setOther(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();addOther()}}}/></label><button className="secondary" onClick={addOther}>+ Adicionar outro</button></div>}<div className="custom-chips">{chosen.filter(x=>!options.includes(x)).map(x=><button key={x} onClick={()=>setChosen(v=>v.filter(i=>i!==x))}>{x} ×</button>)}</div></>}{step===2&&<><h1>Um combinado simples.</h1><div className="principles"><p><b>Você escolhe o objetivo.</b><br/>Sua família revisa a jornada antes de aprovar.</p><p><b>Progresso vem do que você faz.</b><br/>O XP entra depois da validação.</p><p><b>Seu espaço é privado.</b><br/>Cada família acessa somente seus próprios dados.</p></div></>}{error&&<Alert>{error}</Alert>}<button className="primary" disabled={(youth&&step===0&&!birthDate)||(step===1&&chosen.length<2)} onClick={()=>step<2?setStep(step+1):finish()}>{step<2?'Continuar':'Entrar na KONKI'}</button></section>
}

function BirthdayCard({state,youthName,isYouth,hasConquest,onCta}:{state:ReturnType<typeof getBirthdayState>;youthName:string;isYouth:boolean;hasConquest:boolean;onCta:()=>void}){const remaining=state.monthsUntil?`${state.monthsUntil} ${state.monthsUntil===1?'mês':'meses'}${state.remainingDays?` e ${state.remainingDays} ${state.remainingDays===1?'dia':'dias'}`:''}`:`${state.daysUntil} ${state.daysUntil===1?'dia':'dias'}`;return <section className={`birthday-card birthday-${state.tier.toLowerCase()}`}><span>{state.isBirthday?'SEU NOVO ANO COMEÇOU':state.tier==='DISCREET'?'PRÓXIMO CICLO':'SEU ANIVERSÁRIO ESTÁ CHEGANDO'}</span><h2>{state.isBirthday?`Feliz aniversário, ${youthName}.`:`Faltam ${remaining} para você fazer ${state.ageTurning}.`}</h2><p>{state.isBirthday?'Um novo ano. Qual vai ser sua próxima conquista?':hasConquest?'Tem alguma coisa que você gostaria de conquistar depois?':'Planejar com antecedência deixa tudo mais possível.'}</p>{isYouth&&<button className={state.tier==='DISCREET'?'secondary wide':'primary'} onClick={onCta}>{hasConquest?'Guardar uma ideia':'Planejar minha conquista'}</button>}</section>}

function Dashboard({profile,family,go}:{profile:Profile;family:Family|null;go:Go}){
  const[conquest,setConquest]=useState<any>(null),[assignments,setAssignments]=useState<Assignment[]>([]),[youth,setYouth]=useState<any>(null),[pending,setPending]=useState(0),[draftJourney,setDraftJourney]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
  const load=useCallback(async()=>{setLoading(true);setError('');const c=await supabase.from('conquests').select('*').in('status',['PENDING','CHANGES_REQUESTED','APPROVED','ACTIVE']).order('created_at',{ascending:false}).limit(1).maybeSingle();if(c.error){setError('Não conseguimos carregar sua conquista.');setLoading(false);return}let draft:any=null;if(profile.role==='PARENT'){const j=await supabase.from('journeys').select('*').eq('status','DRAFT').order('created_at',{ascending:false}).limit(1).maybeSingle();if(j.error){setError('Não conseguimos carregar as pendências da família.');setLoading(false);return}draft=j.data}const a=await supabase.from('mission_assignments').select('id,status,recommendation_reasons,conquest_id,journey_id,mission_order,mission:missions(*)').order('mission_order',{ascending:true,nullsFirst:false}).limit(30);if(a.error){setError('Não conseguimos carregar as missões da família.');setLoading(false);return}const y=profile.role==='YOUTH'?await supabase.from('youth_profiles').select('*').eq('profile_id',profile.id).single():await supabase.from('youth_profiles').select('*,profiles(first_name)').limit(1).maybeSingle();if(y.error){setError('Não conseguimos carregar o perfil da jornada.');setLoading(false);return}setConquest(c.data);setDraftJourney(draft);setAssignments((a.data||[]) as unknown as Assignment[]);setYouth(y.data);setPending(profile.role==='PARENT'?(a.data||[]).filter(x=>x.status==='SUBMITTED').length:0);setLoading(false)},[profile.id,profile.role]);
  useEffect(()=>{load()},[load]);
  const readableStatus:Record<string,string>={PENDING:'Aguardando revisão da jornada',APPROVED:'Jornada aprovada',ACTIVE:'Jornada em andamento',COMPLETED:'Conquista concluída'};
  const birthday=profile.role==='YOUTH'&&youth?.birth_date?getBirthdayState(youth.birth_date):null;
  if(loading)return <LoadingState label="Carregando painel…"/>;if(error)return <RetryState message={error} onRetry={load}/>;
  return <><section className="hello"><span>{profile.role==='PARENT'?'ACOMPANHAMENTO':'SUA JORNADA'}</span><h1>Olá, {profile.first_name}.</h1><p>{profile.role==='PARENT'?`Tudo que acontece em ${family?.name||'sua família'}, num só lugar.`:'Seu próximo passo pode ser pequeno. A conquista, não.'}</p></section>{birthday&&<BirthdayCard state={birthday} youthName={profile.role==='YOUTH'?profile.first_name:youth?.profiles?.first_name||'o jovem'} isYouth={profile.role==='YOUTH'} hasConquest={Boolean(conquest)} onCta={()=>go(conquest?'wishlist':'conquest')}/>} {profile.role==='PARENT'&&(draftJourney||pending>0)&&<section className="attention"><span>O QUE PRECISA DA SUA ATENÇÃO</span>{draftJourney&&<div><b>{youth?.profiles?.first_name||'O jovem'} criou uma conquista.</b><p>A proposta de missões está pronta para você revisar.</p><button className="primary" onClick={()=>go('journey-review',{journeyId:draftJourney.id})}>Revisar jornada</button></div>}{pending>0&&<div><b>{pending} {pending===1?'missão aguarda':'missões aguardam'} validação.</b><button className="secondary wide" onClick={()=>go('review')}>Ver e validar</button></div>}</section>}{conquest?<><button className="goal-card" onClick={()=>go(profile.role==='PARENT'&&conquest.status==='PENDING'?'journey-review':'conquest',profile.role==='PARENT'&&draftJourney?{journeyId:draftJourney.id}:{})}><div className="goal-top"><div><span>{profile.role==='YOUTH'?'SUA CONQUISTA':'CONQUISTA ATUAL'}</span><h2>{conquest.title}</h2></div><b>{Number(conquest.progress).toFixed(0)}% conquistado</b></div><Progress value={conquest.progress}/><div className="goal-meta"><span>{readableStatus[conquest.status]||conquest.status}</span><span>Faltam {(100-Number(conquest.progress)).toFixed(0)}%</span><span>{conquest.confirmed_goal_value?moneyBRL(Number(conquest.confirmed_goal_value)):'Valor será combinado'}</span></div></button>{profile.role==='YOUTH'&&<button className="new-conquest-link" onClick={()=>go('wishlist')}>+ Nova conquista</button>}</>:<section className="empty-card"><Mark/><h2>{profile.role==='YOUTH'?'Escolha sua primeira conquista':'Aguardando o objetivo do jovem'}</h2><p>{profile.role==='YOUTH'?'Pode ser algo para comprar, viver ou aprender.':'Compartilhe o convite e acompanhe quando ele entrar.'}</p>{profile.role==='YOUTH'&&<button className="primary" onClick={()=>go('conquest')}>Criar conquista</button>}</section>}
    <div className="stats"><div><b>{youth?.total_xp||0}</b><small>XP</small></div><div><b>{youth?.streak_weeks||0}</b><small>semanas</small></div><div><b>{assignments.filter(a=>a.status==='APPROVED').length}</b><small>aprovadas</small></div><div><b>{pending}</b><small>para revisar</small></div></div>
    <div className="section-heading"><div><span>AGORA</span><h2>{profile.role==='PARENT'?'Atividade da família':'Próximas missões'}</h2></div><button onClick={()=>go(profile.role==='PARENT'?'review':'missions')}>Ver tudo</button></div>{assignments.length?<MissionCards items={assignments.slice(0,3)} open={id=>go(profile.role==='PARENT'?'review':'mission',{assignmentId:id})}/>:<section className="empty-inline"><p>As recomendações aparecem quando o contrato for aceito.</p></section>}
  </>
}

function Conquest({profile,family,go}:{profile:Profile;family:Family|null;go:Go}){
  const[current,setCurrent]=useState<any>(null),[draftJourneyId,setDraftJourneyId]=useState<string|undefined>(),[title,setTitle]=useState(''),[reason,setReason]=useState(''),[message,setMessage]=useState(''),[messageKind,setMessageKind]=useState<'error'|'success'>('error'),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('');const load=useCallback(async()=>{setLoading(true);setError('');const result=await supabase.from('conquests').select('*').in('status',['PENDING','CHANGES_REQUESTED','APPROVED','ACTIVE']).order('created_at',{ascending:false}).limit(1).maybeSingle();if(result.error){setError('Não conseguimos carregar a conquista principal.');setLoading(false);return}setCurrent(result.data);setDraftJourneyId(undefined);if(result.data&&profile.role==='PARENT'&&result.data.status==='PENDING'){const journey=await supabase.from('journeys').select('id').eq('conquest_id',result.data.id).eq('status','DRAFT').maybeSingle();if(journey.error){setError('Não conseguimos confirmar a proposta desta conquista.');setLoading(false);return}setDraftJourneyId(journey.data?.id)}setLoading(false)},[profile.role]);useEffect(()=>{load()},[load]);
  const generate=async(conquestId:string)=>{const{data:{session}}=await supabase.auth.getSession();const response=await fetch('/api/missions/recommend',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${session?.access_token}`},body:JSON.stringify({conquestId})});const generated=await response.json() as ApiResponse;if(!response.ok)throw new Error(generated.error||'Não foi possível preparar a jornada.');return generated};
  const create=async(e:FormEvent)=>{e.preventDefault();if(!family||busy)return;setBusy(true);setMessage('Preparando sua jornada…');setMessageKind('success');try{const check=await supabase.from('conquests').select('*').in('status',['PENDING','CHANGES_REQUESTED','APPROVED','ACTIVE']).order('created_at',{ascending:false}).limit(1).maybeSingle();if(check.error)throw check.error;if(check.data){setCurrent(check.data);setMessage('Você já está correndo atrás de uma conquista.');return}const{data:conquestId,error:failure}=await supabase.rpc('create_conquest',{conquest_title:title,conquest_category:'OTHER',conquest_reason:reason||null});if(failure)throw failure;const created=await supabase.from('conquests').select('*').eq('id',conquestId).single();if(created.error)throw created.error;const generated=await generate(conquestId);setCurrent({...created.data,recommended_mission_count:generated.missionCount,cadence_label:`${generated.suggestedWeeks} semanas sugeridas`});setMessageKind('success');setMessage('Proposta criada. Seu responsável já pode revisar a jornada.')}catch(failure){setMessageKind('error');setMessage(friendlyError(failure,'Não foi possível preparar sua jornada. Tente novamente.'))}finally{setBusy(false)}};
  const retryGeneration=async()=>{if(!current||busy)return;setBusy(true);setMessage('Preparando as missões…');setMessageKind('success');try{await generate(current.id);await load();setMessage('Proposta concluída e enviada ao responsável.')}catch(failure){setMessageKind('error');setMessage(friendlyError(failure,'A conquista existe, mas a proposta ainda não foi concluída. Tente novamente.'))}finally{setBusy(false)}};
  const discardIncomplete=async()=>{if(!current||busy||!confirm('Descartar esta conquista incompleta?'))return;setBusy(true);const{error:failure}=await supabase.rpc('discard_incomplete_conquest',{target_conquest:current.id,discard_reason:'Descartada pelo jovem antes da geração da jornada'});if(failure){setMessageKind('error');setMessage(friendlyError(failure,'Não foi possível descartar a conquista. Tente novamente.'))}else{setCurrent(null);setMessageKind('success');setMessage('Conquista incompleta descartada. Você pode criar uma nova.')}setBusy(false)};
  const resubmit=async(e:FormEvent)=>{e.preventDefault();if(!current||busy)return;setBusy(true);setMessage('Recriando a proposta…');setMessageKind('success');try{const{data:conquestId,error:failure}=await supabase.rpc('resubmit_conquest',{target_conquest:current.id,conquest_title:title||current.title,conquest_reason:reason||current.reason||null});if(failure)throw failure;await generate(conquestId);setMessage('Proposta reformulada e enviada ao responsável.');setMessageKind('success');await load()}catch(failure){setMessageKind('error');setMessage(friendlyError(failure,'Não foi possível reformular a conquista. Tente novamente.'))}finally{setBusy(false)}};
  if(loading)return <LoadingState label="Carregando conquista…"/>;if(error)return <RetryState message={error} onRetry={load}/>;if(!current&&profile.role==='YOUTH')return <><Header over="NOVA CONQUISTA" title="O que você quer conquistar?" text="Conte sua ideia. Prazo e combinado ficam para o responsável revisar."/><form onSubmit={create} className="form-stack panel"><label>Sua conquista<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ex.: quero comprar um casaco" required/></label><label>Por que isso é importante para você?<textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Opcional"/></label><button className="primary" disabled={busy}>{busy?'Preparando sua jornada…':'Criar minha jornada'}</button><button type="button" className="secondary" disabled={busy} onClick={()=>go('wishlist')}>Ver minha lista de desejos</button></form>{message&&<Alert kind={messageKind}>{message}</Alert>}</>;
  if(current?.status==='CHANGES_REQUESTED'&&profile.role==='YOUTH')return <><Header over="REFORMULAR CONQUISTA" title="Seu responsável pediu ajustes" text={current.rejection_reason||'Revise seu objetivo e envie uma nova proposta.'}/><form onSubmit={resubmit} className="form-stack panel"><label>Sua conquista<input value={title||current.title} onChange={e=>setTitle(e.target.value)} required/></label><label>Por que isso é importante?<textarea value={reason||current.reason||''} onChange={e=>setReason(e.target.value)}/></label><button className="primary" disabled={busy}>{busy?'Recriando…':'Reformular e enviar novamente'}</button><button type="button" className="secondary danger-outline" onClick={()=>go('archive')}>Encerrar esta conquista</button></form>{message&&<Alert kind={messageKind}>{message}</Alert>}</>;
  return <><Header over="CONQUISTA PRINCIPAL" title={current?.title||'Ainda sem objetivo'} text={current?.reason||'Quando o jovem criar o objetivo, ele aparece aqui.'}/>{current&&<section className="panel"><div className="status-line"><span>Status</span><b>{current.status==='PENDING'&&!current.recommended_mission_count?'Proposta incompleta':current.status==='PENDING'?'Aguardando revisão da jornada':current.status==='ACTIVE'?'Jornada em andamento':current.status==='CHANGES_REQUESTED'?'Reformulação solicitada':'Jornada aprovada'}</b></div><div className="progress-big"><b>{Number(current.progress).toFixed(2)}%</b><span>concluído · faltam {(100-Number(current.progress)).toFixed(2)}%</span></div><Progress value={current.progress}/>{current.estimated_duration_months&&<p>{current.estimated_duration_months} meses · {current.recommended_mission_count} missões · {current.cadence_label}</p>}{profile.role==='YOUTH'&&current.status==='PENDING'&&!current.recommended_mission_count&&<><Alert>A conquista foi salva, mas a proposta de missões ainda não foi concluída.</Alert><button className="primary" disabled={busy} onClick={retryGeneration}>{busy?'Preparando…':'Concluir preparação da jornada'}</button><button className="secondary danger-outline wide" disabled={busy} onClick={discardIncomplete}>Descartar conquista incompleta</button></>}{profile.role==='PARENT'&&current.status==='PENDING'&&draftJourneyId&&<button className="primary" onClick={()=>go('journey-review',{journeyId:draftJourneyId})}>Revisar jornada e definir combinado</button>}{profile.role==='PARENT'&&current.status==='PENDING'&&!draftJourneyId&&<Alert>A proposta ainda não foi concluída pelo jovem.</Alert>}{current.status==='ACTIVE'&&<button className="primary" onClick={()=>go('contract')}>Ver combinado</button>}{profile.role==='PARENT'&&['APPROVED','ACTIVE'].includes(current.status)&&<button className="secondary wide" onClick={()=>go('missions')}>Ver plano completo</button>}<div className="action-row">{profile.role==='YOUTH'&&<button className="secondary" onClick={()=>go('wishlist')}>Lista de desejos</button>}{!(profile.role==='YOUTH'&&current.status==='PENDING'&&!current.recommended_mission_count)&&<button className="secondary danger-outline" onClick={()=>go('archive')}>Encerrar jornada</button>}</div></section>}{!current&&profile.role==='PARENT'&&<section className="empty-card"><p>Não há conquista principal ativa.</p></section>}{message&&<Alert kind={messageKind}>{message}</Alert>}</>
}

function Wishlist({profile,family,go}:{profile:Profile;family:Family|null;go:(v:View)=>void}){const[items,setItems]=useState<any[]>([]),[title,setTitle]=useState(''),[context,setContext]=useState(''),[message,setMessage]=useState('');const load=useCallback(()=>supabase.from('conquest_wishlist').select('*').order('created_at',{ascending:false}).then(({data})=>setItems(data||[])),[]);useEffect(()=>{load()},[load]);const add=async(e:FormEvent)=>{e.preventDefault();if(!family)return;const{error}=await supabase.rpc('save_wishlist_item',{item_title:title,item_context:context||null,item_category:null});if(error)return setMessage(error.message);setTitle('');setContext('');setMessage('Ideia guardada.');load()};const remove=async(id:string)=>{const{error}=await supabase.rpc('remove_wishlist_item',{target_item:id});if(error)setMessage(error.message);else load()};const activate=async(id:string)=>{setMessage('Preparando sua nova jornada…');const{data,error}=await supabase.rpc('activate_wishlist_item',{target_item:id});if(error)return setMessage(error.message.includes('active_conquest')?'Finalize a conquista atual antes de ativar outra.':error.message);const{data:{session}}=await supabase.auth.getSession();const r=await fetch('/api/missions/recommend',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${session?.access_token}`},body:JSON.stringify({conquestId:data})});if(!r.ok)return setMessage('A conquista foi ativada, mas a jornada precisa ser gerada novamente.');go('conquest')};return <><button className="back" onClick={()=>go('conquest')}>‹ Conquista</button><Header over="PRÓXIMAS IDEIAS" title="Lista de desejos" text={profile.role==='YOUTH'?'Guarde ideias sem trocar sua conquista principal.':'Ideias que o jovem guardou para depois.'}/>{profile.role==='YOUTH'&&<form className="panel form-stack" onSubmit={add}><label>O que você gostaria de conquistar?<input value={title} onChange={e=>setTitle(e.target.value)} required/></label><label>Por que essa ideia é legal?<textarea value={context} onChange={e=>setContext(e.target.value)}/></label><button className="primary">Guardar ideia</button></form>}<div className="wishlist-grid">{items.map(item=><article className="panel" key={item.id}><span className="status-pill">{item.status==='SAVED'?'GUARDADA':item.status}</span><h2>{item.title}</h2>{item.context&&<p>{item.context}</p>}{profile.role==='YOUTH'&&item.status==='SAVED'&&<div className="action-row"><button className="secondary danger-outline" onClick={()=>remove(item.id)}>Remover</button><button className="primary" onClick={()=>activate(item.id)}>Tornar principal</button></div>}</article>)}</div>{!items.length&&<section className="empty-card"><p>Nenhuma ideia guardada ainda.</p></section>}{message&&<Alert kind={message==='Ideia guardada.'?'success':'error'}>{message}</Alert>}</>}

function ArchiveJourney({go}:{go:(v:View)=>void}){const[journey,setJourney]=useState<any>(null),[history,setHistory]=useState<any[]>([]),[reason,setReason]=useState('Mudei de objetivo'),[other,setOther]=useState(''),[message,setMessage]=useState('');useEffect(()=>{supabase.from('journeys').select('*,conquest:conquests(*)').in('status',['DRAFT','CHANGES_REQUESTED','APPROVED','ACTIVE']).order('created_at',{ascending:false}).limit(1).maybeSingle().then(({data})=>setJourney(data));supabase.from('journey_archive_events').select('*').order('created_at',{ascending:false}).then(({data})=>setHistory(data||[]))},[]);const archive=async()=>{if(!journey)return;const finalReason=reason==='Outro'?other.trim():reason;if(!finalReason)return setMessage('Conte o motivo para continuar.');if(!confirm('Encerrar esta jornada? O XP e o histórico serão preservados.'))return;const{error}=await supabase.rpc('archive_journey',{target_journey:journey.id,archive_reason:finalReason});if(error)return setMessage(friendlyError(error,'Não foi possível encerrar a jornada. Tente novamente.'));setMessage('Jornada encerrada. XP, evidências e histórico foram preservados.');setJourney(null)};return <><button className="back" onClick={()=>go('conquest')}>‹ Conquista</button><Header over="ENCERRAR COM CONSCIÊNCIA" title="Encerrar jornada" text="Parar ou mudar de ideia também faz parte. Nada do que você já conquistou será apagado."/>{journey?<section className="panel"><h2>{journey.conquest.title}</h2><div className="status-line"><span>Progresso preservado</span><b>{Number(journey.conquest.progress).toFixed(2)}%</b></div><label>Por que a jornada vai terminar?<select value={reason} onChange={e=>setReason(e.target.value)}><option>Mudei de objetivo</option><option>O momento não é mais adequado</option><option>O combinado da família mudou</option><option>Outro</option></select></label>{reason==='Outro'&&<label>Conte um pouco<textarea value={other} onChange={e=>setOther(e.target.value)} required/></label>}<button className="secondary danger-outline" onClick={archive}>Encerrar e preservar histórico</button></section>:<section className="empty-card"><p>Nenhuma jornada em andamento.</p><button className="primary" onClick={()=>go('conquest')}>Voltar às conquistas</button></section>}{message&&<Alert kind={message.startsWith('Jornada encerrada')?'success':'error'}>{message}</Alert>}{history.length>0&&<><h2 className="subheading">Jornadas anteriores</h2>{history.map(h=><article className="panel" key={h.id}><div className="status-line"><span>{new Date(h.created_at).toLocaleDateString('pt-BR')}</span><b>{Number(h.progress_at_archive).toFixed(2)}%</b></div><p>{h.reason}</p><small>{h.approved_missions} missões aprovadas · {h.earned_xp} XP preservados</small></article>)}</>}</>}

type JourneyMission={id:string;journey_id:string;family_id:string;source_mission_id:string|null;title:string;description:string;instructions:string;category:string;skills:string[];estimated_minutes:number;xp_reward:number;evidence_types:string[];phase:number;mission_order:number;recommendation_reasons:string[];is_custom:boolean;why_this_mission?:string;effort_weight:number;progress_percentage:number;contextualized_micro_lesson?:string;contextualized_steps?:string[];contextualized_evidence_request?:string};
const phaseNames=['ENTENDER O OBJETIVO','APRENDER E PLANEJAR','COLOCAR EM PRÁTICA','CONQUISTAR'];
function JourneyReview({go,journeyId}:{go:Go;journeyId?:string}){
  const[journey,setJourney]=useState<any>(null),[items,setItems]=useState<JourneyMission[]>([]),[goals,setGoals]=useState<string[]>([]),[likes,setLikes]=useState<string[]>([]),[editing,setEditing]=useState<JourneyMission|null>(null),[adding,setAdding]=useState<'choice'|'catalog'|'custom'|null>(null),[catalog,setCatalog]=useState<Mission[]>([]),[search,setSearch]=useState(''),[message,setMessage]=useState(''),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(''),[busy,setBusy]=useState(false),[duration,setDuration]=useState(3),[desiredDate,setDesiredDate]=useState(''),[goalValue,setGoalValue]=useState(''),[reward,setReward]=useState('Reconhecer o esforço e cumprir o combinado quando a jornada chegar a 100%.'),[rejectReason,setRejectReason]=useState('');
  const load=useCallback(async()=>{setLoading(true);setLoadError('');setItems([]);let query=supabase.from('journeys').select('*,conquest:conquests(*)').eq('status','DRAFT');query=journeyId?query.eq('id',journeyId):query.order('created_at',{ascending:false}).limit(1);const j=await query.maybeSingle();if(j.error){setLoadError('Não conseguimos carregar esta jornada. Tente novamente.');setLoading(false);return}setJourney(j.data);if(!j.data){if(journeyId)setLoadError('Esta jornada não foi encontrada ou não está mais aguardando revisão.');setLoading(false);return}setDuration(j.data.agreed_duration_months||j.data.estimated_duration_months||3);setDesiredDate(j.data.conquest.desired_date||'');setGoalValue(j.data.conquest.confirmed_goal_value||j.data.conquest.approximate_value||'');setReward(j.data.conquest.reward_agreement||'Reconhecer o esforço e cumprir o combinado quando a jornada chegar a 100%.');const[m,yp,pp]=await Promise.all([supabase.from('journey_missions').select('*').eq('journey_id',j.data.id).order('mission_order'),supabase.from('youth_profiles').select('interests').eq('profile_id',j.data.youth_id).single(),supabase.from('parent_profiles').select('development_goals').limit(1).maybeSingle()]);if(m.error||yp.error||pp.error){setLoadError('A jornada existe, mas não conseguimos carregar todos os detalhes. Tente novamente.');setLoading(false);return}if(!m.data?.length){setLoadError('As missões ainda estão sendo preparadas. Tente novamente em instantes.');setLoading(false);return}setItems(m.data as JourneyMission[]);setLikes(yp.data?.interests||[]);setGoals(pp.data?.development_goals||[]);if(!journeyId)history.replaceState(null,'',appRouteUrl({view:'journey-review',journeyId:j.data.id}));setLoading(false)},[journeyId]);
  useEffect(()=>{load()},[load]);
  const save=async(m:JourneyMission)=>{const original=items.find(x=>x.id===m.id);const substantial=Boolean(original&&(original.description.trim()!==m.description.trim()||original.instructions.trim()!==m.instructions.trim()));const parentCustom=Boolean(original?.is_custom||substantial);const update:any={title:m.title,description:m.description,instructions:m.instructions,estimated_minutes:m.estimated_minutes,xp_reward:m.xp_reward,skills:m.skills,evidence_types:m.evidence_types,effort_weight:m.effort_weight,is_custom:parentCustom,updated_at:new Date().toISOString()};if(substantial)Object.assign(update,{contextualized_intro:null,contextualized_micro_lesson:null,contextualized_steps:null,contextualized_evidence_request:null,follow_up_question:null,why_this_mission:null,technique_explanation:null,contextualized_example:null,autonomy_guidance:null,parent_support_guidance:null,reflection_depth:null,evidence_checklist:null});const{error}=await supabase.from('journey_missions').update(update).eq('id',m.id);if(error)setMessage(friendlyError(error,'Não foi possível salvar a missão. Tente novamente.'));else{setEditing(null);setMessage(substantial?'Missão transformada em personalizada. Progresso recalculado.':'Missão salva com o conteúdo KONKI preservado. Progresso recalculado.');load()}};
  const remove=async(m:JourneyMission)=>{if(!confirm('Remover esta missão da jornada?'))return;const{error}=await supabase.from('journey_missions').delete().eq('id',m.id);if(error)setMessage(error.message);else{setMessage('Missão removida da jornada.');load()}};
  const move=async(index:number,delta:number)=>{const other=items[index+delta],current=items[index];if(!other)return;await supabase.from('journey_missions').update({mission_order:1000+current.mission_order}).eq('id',current.id);await supabase.from('journey_missions').update({mission_order:current.mission_order}).eq('id',other.id);await supabase.from('journey_missions').update({mission_order:other.mission_order}).eq('id',current.id);load()};
  const openCatalog=async()=>{const c=await supabase.from('missions').select('*').is('family_id',null).eq('status','ACTIVE').order('title');setCatalog((c.data||[]) as Mission[]);setAdding('catalog')};
  const addCatalog=async(m:Mission)=>{if(!journey)return;const order=Math.max(0,...items.map(x=>x.mission_order))+1;const{error}=await supabase.from('journey_missions').insert({journey_id:journey.id,family_id:journey.family_id,source_mission_id:m.id,title:m.title,description:m.description,instructions:m.description,category:m.category,skills:m.skills,estimated_minutes:m.estimated_minutes,xp_reward:m.xp_reward,goal_progress_reward:Math.max(1,Math.floor(100/(items.length+1))),evidence_types:m.evidence_types,phase:4,mission_order:order,recommendation_reasons:['Escolhida pelo responsável'],is_custom:false});if(error)setMessage(error.message);else{setAdding(null);setMessage('Missão adicionada.');load()}};
  const addCustom=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!journey)return;const f=new FormData(e.currentTarget),minutes=Number(f.get('minutes')),xp=Number(f.get('xp'));const selected=f.getAll('skills').map(String),evidence=f.getAll('evidence').map(String);const order=Math.max(0,...items.map(x=>x.mission_order))+1;const{error}=await supabase.from('journey_missions').insert({journey_id:journey.id,family_id:journey.family_id,title:String(f.get('title')),description:String(f.get('instructions')),instructions:String(f.get('instructions')),category:'Vida real',skills:selected,estimated_minutes:minutes,xp_reward:xp,goal_progress_reward:Math.max(1,Math.floor(100/(items.length+1))),evidence_types:evidence.length?evidence:['TEXT'],phase:4,mission_order:order,recommendation_reasons:['Criada pelo responsável'],is_custom:true});if(error)setMessage(error.message);else{setAdding(null);setMessage('Missão personalizada adicionada.');load()}};
  const approve=async()=>{if(!journey)return;if(duration<1||duration>36)return setMessage('Defina uma duração entre 1 e 36 meses.');if(desiredDate&&new Date(`${desiredDate}T12:00:00`)<new Date())return setMessage('Escolha uma data futura para a conquista.');setBusy(true);const{data,error}=await supabase.rpc('approve_journey_with_deadline',{target_journey:journey.id,goal_value:goalValue?Number(goalValue):null,reward_text:reward||null,duration_months:duration,goal_deadline:desiredDate||null});setBusy(false);if(error)setMessage(friendlyError(error,'Não foi possível aprovar a jornada. Tente novamente.'));else{setMessage(`Jornada aprovada com ${data.mission_count} missões.`);setTimeout(()=>go('home'),900)}};
  const reject=async()=>{if(!journey)return;if(!rejectReason.trim())return setMessage('Explique ao jovem o que precisa ser reformulado.');if(!confirm('Pedir reformulação desta conquista? Nenhuma missão será ativada.'))return;setBusy(true);const{error}=await supabase.rpc('reject_journey',{target_journey:journey.id,rejection_reason:rejectReason.trim()});setBusy(false);if(error)setMessage(friendlyError(error,'Não foi possível pedir a reformulação. Tente novamente.'));else{setMessage('Reformulação solicitada ao jovem.');setTimeout(()=>go('home'),900)}};
  if(loading)return <LoadingState label="Preparando as missões…"/>;if(loadError)return <><button className="back" onClick={()=>go('home')}>‹ Início</button><RetryState message={loadError} onRetry={load}/></>;if(!journey)return <><Header over="RESPONSÁVEL" title="Nenhuma jornada para revisar" text="Quando o jovem criar uma conquista, a proposta aparece aqui."/><button className="secondary wide" onClick={()=>go('home')}>Voltar ao início</button></>;
  const filtered=catalog.filter(m=>!items.some(x=>x.source_mission_id===m.id)&&`${m.title} ${m.description} ${m.category}`.toLowerCase().includes(search.toLowerCase()));
  return <><button className="back" onClick={()=>go('home')}>‹ Início</button><Header over="ANTES DE APROVAR" title="Revise a jornada" text="A KONKI montou esta proposta com base no objetivo, nos interesses e no que você quer desenvolver."/><section className="context-card conquest-context"><small>CONQUISTA</small><h2>{journey.conquest.title}</h2><b>Por que isso importa</b><p>{journey.conquest.reason||'O jovem não informou um motivo.'}</p></section><section className="journey-summary"><div><small>STATUS</small><b>Aguardando revisão</b></div><div><small>DURAÇÃO ESTIMADA</small><b>{journey.cadence_label||`${journey.estimated_duration_months} meses`}</b></div><div><small>MISSÕES</small><b>{items.length}</b></div><div><small>PROGRESSO TOTAL</small><b>{items.reduce((sum,m)=>sum+Number(m.progress_percentage||0),0).toFixed(2)}%</b></div></section><section className="context-card"><div><b>Competências</b><div className="skill-row">{[...new Set([...goals,...items.flatMap(m=>m.skills||[])])].map(x=><span key={x}>{x}</span>)}</div></div><div><b>Interesses</b><div className="skill-row">{likes.map(x=><span key={x}>{x}</span>)}</div></div></section>
  <section className="context-card"><div><b>Distribuição do progresso</b><p>Cada missão representa uma parte do esforço total. Soma atual: {items.reduce((sum,m)=>sum+Number(m.progress_percentage||0),0).toFixed(2)}%.</p></div></section>
  {phaseNames.map((phase,p)=><section className="journey-phase" key={phase}><header><span>FASE {p+1}</span><h2>{phase}</h2></header>{items.map((m,i)=>m.phase===p+1&&<article className="journey-mission" key={m.id}><span className="mission-number">{i+1}</span><div><span className="status-pill">{m.is_custom?'MISSÃO DO RESPONSÁVEL':'MISSÃO KONKI'}</span><h3>{m.title}</h3><p>{m.description}</p><p><b>{Number(m.progress_percentage||0).toFixed(2)}% do objetivo</b> · peso {m.effort_weight} · {m.estimated_minutes} min · +{m.xp_reward} XP</p><p><b>Competências:</b> {(m.skills||[]).map(skillLabel).join(', ')||'A definir'} · <b>Evidência:</b> {(m.evidence_types||[]).map(evidenceLabel).join(', ')}</p>{m.why_this_mission&&<small><b>Por que foi recomendada:</b> {m.why_this_mission}</small>} {!m.is_custom&&m.contextualized_micro_lesson&&<details className="pedagogy-preview"><summary>Ver conteúdo pedagógico</summary><p>{m.contextualized_micro_lesson}</p></details>}<div className="mission-actions"><button onClick={()=>setEditing(m)}>Editar</button><button onClick={()=>move(i,-1)} disabled={i===0}>↑</button><button onClick={()=>move(i,1)} disabled={i===items.length-1}>↓</button><button className="remove" onClick={()=>remove(m)}>Remover</button></div></div></article>)}</section>)}
  <button className="add-mission" onClick={()=>setAdding('choice')}>+ Adicionar missão</button><section className="panel agreement-panel"><span className="eyebrow">COMBINADO DO RESPONSÁVEL</span><h2>Defina as condições com clareza</h2><div className="form-row"><label>Duração da jornada (meses)<input type="number" min="1" max="36" value={duration} onChange={e=>setDuration(Number(e.target.value))}/></label><label>Prazo da conquista<input type="date" min={new Date().toISOString().slice(0,10)} value={desiredDate} onChange={e=>setDesiredDate(e.target.value)}/></label></div><label>Valor confirmado (opcional)<input type="number" min="0" step="0.01" value={goalValue} onChange={e=>setGoalValue(e.target.value)} placeholder="R$"/></label><label>O que a família combina ao chegar a 100%?<textarea value={reward} onChange={e=>setReward(e.target.value)}/></label></section><section className="approval-card"><h2>{journey.conquest.title}</h2><p>{duration} meses · {items.length} missões{desiredDate?` · até ${new Date(`${desiredDate}T12:00:00`).toLocaleDateString('pt-BR')}`:''}{goalValue?` · ${moneyBRL(Number(goalValue))}`:''}</p><div className="skill-row">{goals.slice(0,4).map(x=><span key={x}>{x}</span>)}</div><button className="primary" disabled={busy||items.length===0} onClick={approve}>{busy?'Aprovando…':'Aprovar jornada e combinado'}</button><small>Depois da aprovação, responsável e jovem aceitam separadamente antes de começar.</small><div className="reject-box"><label>Não quer aprovar agora?<textarea value={rejectReason} onChange={e=>setRejectReason(e.target.value)} placeholder="Explique o que o jovem precisa reformular."/></label><button className="secondary danger-outline wide" disabled={busy} onClick={reject}>Pedir reformulação</button></div></section>{message&&<Alert kind={message.startsWith('Jornada aprovada')||message.startsWith('Reformulação solicitada')?'success':'error'}>{message}</Alert>}
  {editing&&<div className="modal-backdrop"><section className="modal edit-modal"><button className="close" onClick={()=>setEditing(null)}>×</button><h2>Editar missão</h2><div className="form-stack"><label>Título<input value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})}/></label><label>Descrição<textarea value={editing.description} onChange={e=>setEditing({...editing,description:e.target.value})}/></label><label>O que o jovem precisa fazer<textarea value={editing.instructions} onChange={e=>setEditing({...editing,instructions:e.target.value})}/></label><div className="form-row"><label>Tempo estimado<input type="number" value={editing.estimated_minutes} onChange={e=>setEditing({...editing,estimated_minutes:Number(e.target.value)})}/></label><label>XP<input type="number" value={editing.xp_reward} onChange={e=>setEditing({...editing,xp_reward:Number(e.target.value)})}/></label></div><label>Peso do esforço, de 1 a 5<input type="number" min="1" max="5" value={editing.effort_weight} onChange={e=>setEditing({...editing,effort_weight:Number(e.target.value)})}/></label><label>Competências<input value={editing.skills.join(', ')} onChange={e=>setEditing({...editing,skills:e.target.value.split(',').map(x=>x.trim()).filter(Boolean)})}/></label><label>Tipos de evidência<input value={editing.evidence_types.join(', ')} onChange={e=>setEditing({...editing,evidence_types:e.target.value.split(',').map(x=>x.trim().toUpperCase()).filter(Boolean)})}/></label><button className="primary" onClick={()=>save(editing)}>Salvar</button></div></section></div>}
  {adding&&<div className="modal-backdrop"><section className="modal edit-modal"><button className="close" onClick={()=>setAdding(null)}>×</button>{adding==='choice'&&<><h2>Adicionar missão</h2><button className="option-card" onClick={openCatalog}><b>Escolher uma missão da KONKI</b><small>Veja o catálogo e adicione em um toque.</small></button><button className="option-card" onClick={()=>setAdding('custom')}><b>Criar minha própria missão</b><small>Defina uma atividade para sua família.</small></button></>}{adding==='catalog'&&<><h2>Missões da KONKI</h2><input className="catalog-search" placeholder="Busque vender, organização, viagem…" value={search} onChange={e=>setSearch(e.target.value)}/><div className="catalog-list">{filtered.slice(0,30).map(m=><button key={m.id} onClick={()=>addCatalog(m)}><span><b>{m.title}</b><small>{m.category} · {m.estimated_minutes} min · +{m.xp_reward} XP</small></span><i>+</i></button>)}</div></>}{adding==='custom'&&<><h2>Criar missão</h2><form className="form-stack" onSubmit={addCustom}><label>Título<input name="title" placeholder="Planejar sozinho um almoço" required/></label><label>O que precisa fazer?<textarea name="instructions" required/></label><div className="form-row"><label>Tempo<select name="minutes" defaultValue="30"><option value="15">15 min</option><option value="30">30 min</option><option value="60">1 hora</option></select></label><label>XP sugerido<input name="xp" type="number" defaultValue="150" min="25" max="1000"/></label></div><fieldset className="selection-options"><legend>O que desenvolve?</legend>{skills.map(x=><label className="selection-chip" key={x}><input type="checkbox" name="skills" value={x}/><span>{x}</span></label>)}</fieldset><fieldset className="selection-options"><legend>Como comprovar?</legend>{['TEXT','IMAGE','AUDIO','LINK'].map(x=><label className="selection-chip" key={x}><input type="checkbox" name="evidence" value={x}/><span>{evidenceLabel(x)}</span></label>)}</fieldset><button className="primary">Salvar missão</button></form></>}</section></div>}</>
}

function MissionCards({items,open}:{items:Assignment[];open:(id:string)=>void}){return <div className="mission-stack">{items.map(a=><button className="mission-row" key={a.id} disabled={a.status==='LOCKED'} onClick={()=>a.status!=='LOCKED'&&open(a.id)}><span className="category-mark">{a.mission_order||'•'}</span><span><b>{a.mission.title}</b><small><b>{Number(a.mission.goal_progress_reward).toFixed(2)}% do objetivo</b> · {a.status==='LOCKED'?'Bloqueada até concluir a anterior':labels[a.status]||a.status} · {a.mission.estimated_minutes} min · +{a.mission.xp_reward} XP</small></span><i>{a.status==='LOCKED'?'🔒':'›'}</i></button>)}</div>}
function Missions({go}:{go:Go}){const[items,setItems]=useState<Assignment[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');const load=useCallback(async()=>{setLoading(true);setError('');const result=await supabase.from('mission_assignments').select('id,status,recommendation_reasons,conquest_id,journey_id,mission_order,mission:missions(*)').order('mission_order',{ascending:true,nullsFirst:false});if(result.error)setError('Não conseguimos carregar suas missões.');else setItems((result.data||[]) as unknown as Assignment[]);setLoading(false)},[]);useEffect(()=>{load()},[load]);return <><Header over="SUA JORNADA" title="Missões" text="A ordem faz parte do plano: conclua uma missão para liberar a próxima."/>{loading?<LoadingState label="Carregando missões…"/>:error?<RetryState message={error} onRetry={load}/>:items.length?<MissionCards items={items} open={id=>go('mission',{assignmentId:id})}/>:<section className="empty-card"><h2>Nenhuma missão liberada</h2><p>Depois que o contrato estiver ativo, a KONKI combina habilidades, interesses, idade e objetivo.</p></section>}</>}

function MissionFlow({go,assignmentId}:{go:Go;assignmentId?:string}){
 const[a,setA]=useState<Assignment|null>(null),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(''),[age,setAge]=useState(14),[contractStatus,setContractStatus]=useState(''),[showEvidence,setShowEvidence]=useState(false),[text,setText]=useState(''),[link,setLink]=useState(''),[difficult,setDifficult]=useState(''),[different,setDifferent]=useState(''),[file,setFile]=useState<File|null>(null),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false),[clock,setClock]=useState(0);
 const load=useCallback(async()=>{setLoading(true);setLoadError('');setA(null);if(!assignmentId){setLoadError('O link desta missão é inválido ou está incompleto.');setLoading(false);return}const assignment=await supabase.from('mission_assignments').select('id,status,started_at,recommendation_reasons,conquest_id,journey_id,mission_order,family_id,youth_id,mission:missions(*)').eq('id',assignmentId).single();if(assignment.error||!assignment.data){setLoadError('Missão não encontrada ou sem permissão para esta família.');setLoading(false);return}const[contract,youth]=await Promise.all([supabase.from('conquest_contracts').select('status').eq('conquest_id',(assignment.data as any).conquest_id).maybeSingle(),supabase.from('youth_profiles').select('birth_date,age').eq('profile_id',(assignment.data as any).youth_id).single()]);if(contract.error||youth.error){setLoadError('A missão foi encontrada, mas não foi possível carregar as condições para começar.');setLoading(false);return}setContractStatus(contract.data?.status||'');setAge(youth.data?.birth_date?getBirthdayState(youth.data.birth_date).age:youth.data?.age||14);setA(assignment.data as unknown as Assignment);setShowEvidence((assignment.data as any).status==='NEEDS_CHANGES');setLoading(false)},[assignmentId]);
 useEffect(()=>{load()},[load]);
 useEffect(()=>{if(a?.status!=='STARTED')return;setClock(Date.now());const timer=setInterval(()=>setClock(Date.now()),30000);return()=>clearInterval(timer)},[a?.status]);
 if(loading)return <LoadingState label="Carregando missão…"/>;if(loadError)return <><button className="back" onClick={()=>go('missions')}>‹ Missões</button><RetryState message={loadError} onRetry={load}/></>;if(!a)return null;const raw=a as any,content=a.mission.lesson_content||{},context=typeof content.contexto==='string'?content.contexto:a.mission.description,micro=typeof content.microaula==='string'?content.microaula:'Pare, observe os dados e escolha o próximo passo.',steps=Array.isArray(content.passos)?content.passos as string[]:['Entenda o desafio.','Faça a atividade com dados reais.','Registre o resultado.'],proof=typeof content.prova==='string'?content.prova:'Envie uma explicação do que você fez.',follow=typeof content.follow_up==='string'?content.follow_up:'O que você faria diferente na próxima vez?',technique=typeof content.technique==='string'?content.technique:'Observe, compare, decida e registre.',example=typeof content.example==='string'?content.example:'Compare opções reais antes de escolher.',autonomy=typeof content.autonomy==='string'?content.autonomy:null,parentSupport=typeof content.parent_support==='string'?content.parent_support:null,proofChecklist=Array.isArray(content.evidence_checklist)?content.evidence_checklist as string[]:['Mostre o resultado real','Conte uma decisão que você tomou','Responda o que aprendeu'],guidance=ageGuidance(age);
 const start=async()=>{if(busy)return;setBusy(true);setMsg('');const{error}=await supabase.rpc('start_mission',{target_assignment:a.id});setBusy(false);if(error)return setMsg(error.message.includes('commitment_pending')?'O combinado ainda precisa ser aceito pelo jovem e pelo responsável antes desta missão começar.':friendlyError(error,'Não foi possível iniciar a missão. Tente novamente.'));setA({...a,status:'STARTED',started_at:a.started_at||new Date().toISOString()})};
 const send=async()=>{if(busy)return;setBusy(true);setMsg('');let path:string|null=null;if(file){path=`${raw.family_id}/${raw.youth_id}/${a.id}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const up=await supabase.storage.from('evidence').upload(path,file);if(up.error){setBusy(false);return setMsg(friendlyError(up.error,'Não foi possível enviar o arquivo. Tente novamente.'))}}const evidenceType=file?(file.type.startsWith('audio')?'AUDIO':'IMAGE'):link?'LINK':'TEXT';const{error}=await supabase.from('mission_evidence').insert({assignment_id:a.id,family_id:raw.family_id,youth_id:raw.youth_id,evidence_type:evidenceType,text_content:text||null,link_url:link||null,file_path:path,reflection_difficult:difficult,reflection_different:different});if(error){setBusy(false);return setMsg(friendlyError(error,'Não foi possível salvar sua entrega. Tente novamente.'))}const submitted=await supabase.rpc('submit_mission',{target_assignment:a.id});setBusy(false);if(submitted.error)return setMsg(friendlyError(submitted.error,'Não foi possível enviar para revisão. Tente novamente.'));setA({...a,status:'SUBMITTED'});setShowEvidence(false);setMsg('Mandou bem: sua entrega foi enviada para revisão.')};
 const parentCustom=content.source_type==='PARENT_CUSTOM'||(!content.microaula&&!content.technique&&!Array.isArray(content.passos));
 const allowed=new Set(a.mission.evidence_types||['TEXT']),elapsed=a.started_at?Math.max(0,Math.floor((clock-new Date(a.started_at).getTime())/60000)):0;
 const evidenceForm=<section className="panel evidence-form"><span className="eyebrow">SUA ENTREGA</span><h2>Mostre o que você fez</h2><p>{proof}</p>{allowed.has('TEXT')&&<label>Conte o resultado<textarea value={text} onChange={e=>setText(e.target.value)} placeholder="O que aconteceu? O que você decidiu?"/></label>}{allowed.has('LINK')&&<label>Link da evidência<input type="url" value={link} onChange={e=>setLink(e.target.value)} placeholder="https://…"/></label>}{(allowed.has('IMAGE')||allowed.has('AUDIO'))&&<label>{allowed.has('IMAGE')&&allowed.has('AUDIO')?'Foto ou áudio':allowed.has('IMAGE')?'Foto':'Áudio'}<input type="file" accept={[allowed.has('IMAGE')?'image/*':'',allowed.has('AUDIO')?'audio/*':''].filter(Boolean).join(',')} onChange={e=>setFile(e.target.files?.[0]||null)}/></label>}<label>O que pegou mais?<textarea value={difficult} onChange={e=>setDifficult(e.target.value)}/></label><label>O que você faria diferente?<textarea value={different} onChange={e=>setDifferent(e.target.value)}/></label><button className="primary" disabled={busy||(!text&&!file&&!link)} onClick={send}>{busy?'Enviando…':'Enviar minha entrega'}</button></section>;
 if(a.status==='STARTED'&&!showEvidence)return <><button className="back" onClick={()=>go('missions')}>‹ Continuar depois</button><Header over={`${parentCustom?'MISSÃO DO RESPONSÁVEL':'MISSÃO KONKI'} · EM ANDAMENTO`} title={a.mission.title} text={context}/><section className="mission-running"><div><span>COMEÇOU HÁ</span><b>{elapsed<1?'AGORA':`${elapsed} MIN`}</b></div><div><span>TEMPO SUGERIDO</span><b>{a.mission.estimated_minutes} MIN</b></div></section><section className="panel"><h2>Seu plano agora</h2><ol className="execution-checklist">{steps.map((step,i)=><li key={`${i}-${step}`}>{step}</li>)}</ol><aside className="execution-tip"><b>Dica KONKI</b><p>{guidance.tone}</p></aside><button className="primary" onClick={()=>setShowEvidence(true)}>Terminei a missão</button><button className="secondary wide" onClick={()=>go('missions')}>Continuar depois</button></section>{msg&&<Alert>{msg}</Alert>}</>;
 return <><button className="back" onClick={()=>go('missions')}>‹ Missões</button><Header over={`${parentCustom?'MISSÃO DO RESPONSÁVEL':'MISSÃO KONKI'} · ${statusLabel(a.status)} · ${a.mission.estimated_minutes} MIN`} title={a.mission.title} text={context}/><div className="mission-progress-callout"><b>+{Number(a.mission.goal_progress_reward).toFixed(2)}%</b><span>rumo à sua conquista quando esta missão for aprovada</span></div>{parentCustom?<><details className="learning-block" open><summary>O que você vai fazer</summary><p>{a.mission.description}</p></details><details className="learning-block"><summary>O que enviar</summary><p>{proof}</p></details></>:<><section className="reason-box"><b>Por que isso importa</b><p>{a.recommendation_reasons?.join(' · ')||'Esta missão conecta uma habilidade útil ao seu objetivo.'}</p></section><details className="learning-block" open><summary>O que você vai fazer</summary><p>{a.mission.description}</p>{autonomy&&<p><b>Seu nível de autonomia:</b> {autonomy}</p>}{parentSupport&&<p><b>Apoio do responsável:</b> {parentSupport}</p>}</details><details className="learning-block"><summary>Como fazer, passo a passo</summary><ol>{steps.map((step,i)=><li key={`${i}-${step}`}>{step}</li>)}</ol><p className="age-note"><b>Para você, aos {age}:</b> {guidance.support}</p></details><details className="learning-block"><summary>Aprenda uma coisa nova</summary><h3>{a.mission.lesson_title}</h3><p>{micro}</p><h4>Técnica explicada</h4><p>{technique}</p><h4>Exemplo</h4><p>{example}</p><aside><b>Dica KONKI</b><p>{guidance.tone}</p></aside></details><details className="learning-block"><summary>Agora é com você</summary><p>{follow}</p><div className="skill-row">{a.mission.skills.map(x=><span key={x}>{skillLabel(x)}</span>)}</div></details><details className="learning-block"><summary>O que enviar</summary><p>{proof}</p><ul className="proof-checklist">{proofChecklist.map((item,i)=><li key={`${i}-${item}`}>✓ {item}</li>)}</ul></details></>}{a.status==='AVAILABLE'&&(contractStatus==='ACTIVE'?<button className="primary" disabled={busy} onClick={start}>{busy?'Começando…':'Bora começar'}</button>:<Alert>O combinado ainda precisa ser aceito pelo jovem e pelo responsável. Abra o Combinado para continuar.</Alert>)}{a.status==='LOCKED'&&<Alert>Conclua a missão anterior para liberar esta etapa.</Alert>}{a.status==='NEEDS_CHANGES'&&evidenceForm}{a.status==='SUBMITTED'&&<Alert kind="success">Entrega enviada. O XP e o progresso entram depois da aprovação.</Alert>}{a.status==='APPROVED'&&<Alert kind="success">Missão aprovada. Você avançou de verdade.</Alert>}{msg&&<Alert kind={msg.includes('enviada')?'success':'error'}>{msg}</Alert>}</>
}

function Review(){const[items,setItems]=useState<any[]>([]),[note,setNote]=useState(''),[msg,setMsg]=useState('');const load=()=>supabase.from('mission_assignments').select('*,mission:missions(*),evidence:mission_evidence(*)').eq('status','SUBMITTED').then(({data})=>setItems(data||[]));useEffect(()=>{load()},[]);const act=async(id:string,decision:'approve'|'changes')=>{const{data,error}=decision==='approve'?await supabase.rpc('approve_mission',{target_assignment:id,review_note:note||null}):await supabase.rpc('request_mission_changes',{target_assignment:id,review_note:note||'Complete a evidência.'});setMsg(error?.message||(decision==='approve'?`Aprovada: +${data?.xp_reward||0} XP.`:'Pedido de ajuste enviado.'));load()};return <><Header over="RESPONSÁVEL" title="Revisar evidências" text="Veja a intenção pedagógica antes de validar o esforço."/>{items.length?items.map(a=><section className="panel" key={a.id}><span className="status-pill">AGUARDANDO</span><h2>{a.mission.title}</h2><div className="reason-box"><b>Por que esta missão</b><p>{a.recommendation_reasons?.join(' · ')||a.mission.description}</p></div><div className="skill-row">{a.mission.skills.map((skill:string)=><span key={skill}>{skill}</span>)}</div><p><b>Avanço ao aprovar:</b> {Number(a.mission.goal_progress_reward).toFixed(2)}% · +{a.mission.xp_reward} XP</p>{a.evidence.map((e:any)=><div className="evidence" key={e.id}><p>{e.text_content}</p><blockquote>Mais difícil: {e.reflection_difficult||'Não informado'}<br/>Faria diferente: {e.reflection_different||'Não informado'}</blockquote>{e.file_path&&<PrivateFile path={e.file_path}/>}</div>)}<label>Comentário<textarea value={note} onChange={e=>setNote(e.target.value)}/></label><div className="action-row"><button className="secondary" onClick={()=>act(a.id,'changes')}>Pedir ajuste</button><button className="primary" onClick={()=>act(a.id,'approve')}>Aprovar</button></div></section>):<section className="empty-card"><h2>Tudo revisado</h2><p>Novas entregas aparecem aqui.</p></section>}{msg&&<Alert kind="success">{msg}</Alert>}</>}
function PrivateFile({path}:{path:string}){const[url,setUrl]=useState('');useEffect(()=>{supabase.storage.from('evidence').createSignedUrl(path,300).then(({data})=>setUrl(data?.signedUrl||''))},[path]);return url?<a className="file-link" href={url} target="_blank">Abrir arquivo privado (5 min)</a>:<span>Preparando arquivo…</span>}

function Contract({profile}:{profile:Profile}){
  const[c,setC]=useState<any>(null),[acceptances,setAcceptances]=useState<any[]>([]),[message,setMessage]=useState('');
  const load=useCallback(async()=>{const{data}=await supabase.from('conquest_contracts').select('*,conquest:conquests(*),parent:profiles!conquest_contracts_parent_id_fkey(first_name,last_name),youth:profiles!conquest_contracts_youth_id_fkey(first_name,last_name)').order('created_at',{ascending:false}).limit(1).maybeSingle();setC(data);if(data){const a=await supabase.from('contract_acceptances').select('role,accepted_at').eq('contract_id',data.id);setAcceptances(a.data||[])}},[]);
  useEffect(()=>{load()},[load]);
  const accept=async()=>{if(!c)return;const{data,error}=await supabase.rpc('accept_commitment',{target_contract:c.id});if(error)setMessage(error.message);else{setMessage(data==='ACTIVE'?'Combinado aceito por todos. As missões estão liberadas.':'Sua confirmação foi registrada. Falta a outra pessoa aceitar.');load()}};
  if(!c)return <><Header over="ACORDO" title="Compromisso" text="Ele aparece depois que o responsável revisa e aprova a jornada."/><section className="empty-card"><p>Nenhum compromisso disponível.</p></section></>;
  const accepted=acceptances.some(a=>a.role===profile.role),parentAccepted=acceptances.some(a=>a.role==='PARENT'),youthAccepted=acceptances.some(a=>a.role==='YOUTH');
  return <><Header over="COMPROMISSO DA CONQUISTA" title={c.conquest.title} text="Um combinado mútuo entre jovem e responsável. Não é um contrato jurídico."/><section className="panel contract-card"><span className="status-pill">{c.status==='ACTIVE'?'ATIVO':'AGUARDANDO ACEITES'}</span><div className="status-line"><span>Objetivo</span><b>{c.conquest.title}</b></div><div className="status-line"><span>Prazo combinado</span><b>{c.conquest.desired_date?new Date(`${c.conquest.desired_date}T12:00:00`).toLocaleDateString('pt-BR'):'Sem prazo definido'}</b></div>{c.conquest.confirmed_goal_value&&<div className="status-line"><span>Valor confirmado</span><b>{moneyBRL(Number(c.conquest.confirmed_goal_value))}</b></div>}<div className="status-line"><span>Jornada inicial</span><b>{c.estimated_missions} missões</b></div><div className="status-line"><span>{c.parent?.first_name||'Responsável'}</span><b>{parentAccepted?'Aceitou':'Pendente'}</b></div><div className="status-line"><span>{c.youth?.first_name||'Jovem'}</span><b>{youthAccepted?'Aceitou':'Pendente'}</b></div><blockquote>{c.conquest.reward_agreement||c.conditions}</blockquote>{!accepted&&<button className="primary" onClick={accept}>Li e aceito este combinado</button>}{accepted&&c.status!=='ACTIVE'&&<Alert kind="success">Sua confirmação está registrada. A jornada começa quando a outra pessoa aceitar.</Alert>}<div className="help-text"><b>O que significa progresso?</b><p>É quanto da jornada planejada já foi concluído. XP mostra experiência acumulada, não dinheiro.</p></div></section>{message&&<Alert kind={message.includes('liberadas')?'success':'error'}>{message}</Alert>}</>}

function Notifications(){const[items,setItems]=useState<any[]>([]);const load=()=>supabase.from('notifications').select('*').order('created_at',{ascending:false}).limit(30).then(({data})=>setItems(data||[]));useEffect(()=>{load()},[]);const read=async(id:string)=>{await supabase.rpc('mark_notification_read',{target_notification:id});load()};return <><Header over="CENTRAL" title="Notificações" text="O que pede atenção e o que já avançou."/><div className="notification-list">{items.map(n=><button key={n.id} className={n.read_at?'read':''} onClick={()=>read(n.id)}><i/><span><b>{n.title}</b><small>{n.message}</small></span></button>)}</div></>}

function PilotWishlist({profile,family,go}:{profile:Profile;family:Family|null;go:Go}){
 const[items,setItems]=useState<any[]>([]),[active,setActive]=useState<any>(null),[title,setTitle]=useState(''),[context,setContext]=useState(''),[editing,setEditing]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{setLoading(true);setError('');const[result,conquest]=await Promise.all([supabase.from('conquest_wishlist').select('*').order('created_at',{ascending:false}),supabase.from('conquests').select('id,title,progress,status').in('status',['PENDING','CHANGES_REQUESTED','APPROVED','ACTIVE']).order('created_at',{ascending:false}).limit(1).maybeSingle()]);if(result.error||conquest.error)setError('Não conseguimos carregar sua lista de desejos.');else{setItems(result.data||[]);setActive(conquest.data)}setLoading(false)},[]);useEffect(()=>{load()},[load]);
 const add=async(e:FormEvent)=>{e.preventDefault();if(!family)return;setBusy(true);setMessage('');const{error:failure}=await supabase.rpc('save_wishlist_item',{item_title:title,item_context:context||null,item_category:null});setBusy(false);if(failure)return setMessage(friendlyError(failure,'Não foi possível guardar a ideia. Tente novamente.'));setTitle('');setContext('');setMessage('Ideia guardada.');load()};
 const remove=async(id:string)=>{setBusy(true);setMessage('');const{error:failure}=await supabase.rpc('remove_wishlist_item',{target_item:id});setBusy(false);if(failure)return setMessage(friendlyError(failure,'Não foi possível remover a ideia. Tente novamente.'));load()};
 const saveEdit=async()=>{if(!editing)return;setBusy(true);setMessage('');const{error:failure}=await supabase.rpc('update_wishlist_item',{target_item:editing.id,item_title:editing.title,item_context:editing.context||null});setBusy(false);if(failure)return setMessage(friendlyError(failure,'Não foi possível atualizar a ideia. Tente novamente.'));setEditing(null);setMessage('Ideia atualizada.');load()};
 const activate=async(id:string)=>{if(active){setMessage('Você já está correndo atrás de uma conquista. Guarde esta ideia para depois.');return}setBusy(true);setMessage('Preparando sua jornada…');const{data,error:failure}=await supabase.rpc('activate_wishlist_item',{target_item:id});if(failure){setBusy(false);return setMessage(friendlyError(failure,'Não foi possível ativar esta conquista. Tente novamente.'))}const{data:{session}}=await supabase.auth.getSession();try{const response=await fetch('/api/missions/recommend',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${session?.access_token}`},body:JSON.stringify({conquestId:data})});if(!response.ok){setBusy(false);return setMessage('A conquista foi ativada, mas a jornada precisa ser preparada novamente.')}}catch{setBusy(false);return setMessage('Sem conexão para preparar a jornada. Tente novamente.')}setBusy(false);go('conquest')};
 return <><button className="back" onClick={()=>go('conquest')}>‹ Conquista</button><Header over="QUERO CONQUISTAR DEPOIS" title="Lista de desejos" text={profile.role==='YOUTH'?'Guarde ideias sem trocar sua conquista principal.':'Ideias que o jovem guardou para depois.'}/>{loading?<LoadingState label="Carregando lista de desejos…"/>:error?<RetryState message={error} onRetry={load}/>:<>{profile.role==='YOUTH'&&active&&<section className="panel current-conquest-note"><b>Você já está correndo atrás de uma conquista.</b><div className="status-line"><span>{active.title}</span><b>{Number(active.progress).toFixed(0)}%</b></div><p>Guarde a nova ideia para depois. Sua conquista atual continua igual.</p><button className="secondary wide" onClick={()=>go('conquest')}>Voltar para minha conquista</button></section>}{profile.role==='YOUTH'&&<form className="panel form-stack" onSubmit={add}><label>O que você gostaria de conquistar?<input value={title} onChange={e=>setTitle(e.target.value)} required/></label><label>Quer contar mais alguma coisa?<textarea value={context} onChange={e=>setContext(e.target.value)}/></label><button className="primary" disabled={busy}>{busy?'Aguarde…':active?'Guardar para depois':'Guardar ideia'}</button></form>}<div className="wishlist-grid">{items.map(item=><article className="panel" key={item.id}><span className="status-pill">{item.status==='SAVED'?'GUARDADA':item.status}</span><h2>{item.title}</h2>{item.context&&<p>{item.context}</p>}{profile.role==='YOUTH'&&item.status==='SAVED'&&<><div className="action-row"><button className="secondary" disabled={busy} onClick={()=>setEditing({...item})}>Editar</button><button className="secondary danger-outline" disabled={busy} onClick={()=>remove(item.id)}>Remover</button><button className="primary" disabled={busy||Boolean(active)} onClick={()=>activate(item.id)}>Tornar próxima</button></div>{editing?.id===item.id&&<section className="form-stack inline-edit"><label>Conquista<input value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})}/></label><label>Mais detalhes<textarea value={editing.context||''} onChange={e=>setEditing({...editing,context:e.target.value})}/></label><div className="action-row"><button className="secondary" onClick={()=>setEditing(null)}>Cancelar</button><button className="primary" disabled={busy||!editing.title.trim()} onClick={saveEdit}>Salvar</button></div></section>}</>}</article>)}</div>{!items.length&&<section className="empty-card"><p>Nenhuma ideia guardada ainda.</p></section>}</>}{message&&<Alert kind={['Ideia guardada.','Ideia atualizada.'].includes(message)?'success':'error'}>{message}</Alert>}</>
}

function PilotArchive({go}:{go:Go}){
 const[journey,setJourney]=useState<any>(null),[historyItems,setHistoryItems]=useState<any[]>([]),[metrics,setMetrics]=useState({approved:0,xp:0,minutes:0}),[reason,setReason]=useState('Não quero mais essa conquista'),[other,setOther]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{setLoading(true);setError('');const[journeyResult,historyResult]=await Promise.all([supabase.from('journeys').select('*,conquest:conquests(*)').in('status',['DRAFT','APPROVED','ACTIVE']).order('created_at',{ascending:false}).limit(1).maybeSingle(),supabase.from('journey_archive_events').select('*').order('created_at',{ascending:false})]);if(journeyResult.error||historyResult.error){setError('Não conseguimos carregar a jornada e seu histórico.');setLoading(false);return}setJourney(journeyResult.data);setHistoryItems(historyResult.data||[]);if(journeyResult.data){const assignments=await supabase.from('mission_assignments').select('status,mission:missions(xp_reward,estimated_minutes)').eq('journey_id',journeyResult.data.id);if(assignments.error){setError('Não conseguimos calcular o resumo desta jornada.');setLoading(false);return}const approved=(assignments.data||[]).filter(x=>x.status==='APPROVED');setMetrics({approved:approved.length,xp:approved.reduce((sum,x)=>sum+Number((x.mission as any)?.xp_reward||0),0),minutes:approved.reduce((sum,x)=>sum+Number((x.mission as any)?.estimated_minutes||0),0)})}setLoading(false)},[]);useEffect(()=>{load()},[load]);
 const archive=async()=>{if(!journey)return;const finalReason=reason==='Outro'?other.trim():reason;if(!finalReason)return setMessage('Conte o motivo para continuar.');if(!confirm('Encerrar esta jornada? O XP e o histórico serão preservados.'))return;setBusy(true);setMessage('');const{error:failure}=await supabase.rpc('archive_journey',{target_journey:journey.id,archive_reason:finalReason});setBusy(false);if(failure)return setMessage(friendlyError(failure,'Não foi possível encerrar a jornada. Tente novamente.'));setMessage('Jornada encerrada. XP, evidências e histórico foram preservados.');load()};
 return <><button className="back" onClick={()=>go('conquest')}>‹ Conquista</button><Header over="CONFIGURAÇÕES DA CONQUISTA" title="Encerrar jornada" text="Parar ou mudar de ideia também faz parte. Nada do que você aprendeu será apagado."/>{loading?<LoadingState label="Carregando jornada…"/>:error?<RetryState message={error} onRetry={load}/>:<>{journey?<section className="panel"><h2>{journey.conquest.title}</h2><p>Você já concluiu {metrics.approved} {metrics.approved===1?'missão':'missões'} e chegou a {Number(journey.conquest.progress).toFixed(0)}% desta jornada.</p><div className="status-line"><span>XP preservado</span><b>{metrics.xp}</b></div><div className="status-line"><span>Tempo concluído</span><b>{metrics.minutes} min</b></div><p>Se encerrar esta jornada, o progresso desta conquista será arquivado. Seu XP, missões concluídas e aprendizados continuam no histórico.</p><label>Por que você quer encerrar?<select value={reason} onChange={e=>setReason(e.target.value)}><option>Não quero mais essa conquista</option><option>Quero priorizar outra coisa</option><option>Ficou difícil demais</option><option>Ficou demorado demais</option><option>Outro</option></select></label>{reason==='Outro'&&<label>Conte um pouco<textarea value={other} onChange={e=>setOther(e.target.value)} required/></label>}<button className="secondary danger-outline" disabled={busy} onClick={archive}>{busy?'Encerrando…':'Arquivar jornada'}</button></section>:<section className="empty-card"><p>Nenhuma jornada em andamento.</p>{historyItems.length>0&&<button className="primary" onClick={()=>go('wishlist')}>Escolher uma ideia da wishlist</button>}</section>}{historyItems.length>0&&<><h2 className="subheading">Jornadas anteriores</h2>{historyItems.map(h=><article className="panel" key={h.id}><div className="status-line"><span>{new Date(h.created_at).toLocaleDateString('pt-BR')}</span><b>{Number(h.progress_at_archive).toFixed(2)}%</b></div><p>{h.reason}</p><small>{h.approved_missions} missões aprovadas · {h.earned_xp} XP preservados</small></article>)}</>}</>}{message&&<Alert kind={message.startsWith('Jornada encerrada')?'success':'error'}>{message}</Alert>}</>
}

function PilotReview({assignmentId}:{assignmentId?:string}){
 const[items,setItems]=useState<any[]>([]),[note,setNote]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[success,setSuccess]=useState(false),[busyId,setBusyId]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');let query=supabase.from('mission_assignments').select('*,mission:missions(*),evidence:mission_evidence(*)').eq('status','SUBMITTED');if(assignmentId)query=query.eq('id',assignmentId);const result=await query;if(result.error)setError(assignmentId?'Entrega não encontrada ou sem permissão para esta família.':'Não conseguimos carregar as entregas pendentes.');else setItems(result.data||[]);setLoading(false)},[assignmentId]);useEffect(()=>{load()},[load]);
 const act=async(id:string,decision:'approve'|'changes')=>{setBusyId(id);setMessage('');setSuccess(false);try{const result=decision==='approve'?await supabase.rpc('approve_mission',{target_assignment:id,review_note:note||null}):await supabase.rpc('request_mission_changes',{target_assignment:id,review_note:note||'Complete a evidência.'});if(result.error){setMessage(friendlyError(result.error,'A operação não foi concluída. Tente novamente.'));return}setSuccess(true);setMessage(decision==='approve'?`Missão aprovada: +${result.data?.xp_reward||0} XP.`:'Pedido de ajuste enviado.');await load()}catch{setMessage('Falha de conexão. A entrega não foi alterada; tente novamente.')}finally{setBusyId('')}};
 return <><Header over="RESPONSÁVEL" title="Revisar evidências" text="Veja a intenção pedagógica antes de validar o esforço."/>{loading?<LoadingState label="Carregando entregas…"/>:error?<RetryState message={error} onRetry={load}/>:items.length?items.map(a=><section className="panel" key={a.id}><span className="status-pill">AGUARDANDO</span><h2>{a.mission.title}</h2><div className="reason-box"><b>Por que esta missão</b><p>{a.recommendation_reasons?.join(' · ')||a.mission.description}</p></div><div className="skill-row">{a.mission.skills.map((skill:string)=><span key={skill}>{skill}</span>)}</div><p><b>Avanço ao aprovar:</b> {Number(a.mission.goal_progress_reward).toFixed(2)}% · +{a.mission.xp_reward} XP</p>{a.evidence.map((e:any)=><div className="evidence" key={e.id}><p>{e.text_content}</p><blockquote>Mais difícil: {e.reflection_difficult||'Não informado'}<br/>Faria diferente: {e.reflection_different||'Não informado'}</blockquote>{e.file_path&&<PilotPrivateFile path={e.file_path}/>}</div>)}<label>Comentário<textarea value={note} onChange={e=>setNote(e.target.value)}/></label><div className="action-row"><button className="secondary" disabled={busyId===a.id} onClick={()=>act(a.id,'changes')}>Pedir ajuste</button><button className="primary" disabled={busyId===a.id} onClick={()=>act(a.id,'approve')}>{busyId===a.id?'Aguarde…':'Aprovar'}</button></div></section>):<section className="empty-card"><h2>Tudo revisado</h2><p>{assignmentId?'Esta entrega não está mais pendente.':'Novas entregas aparecem aqui.'}</p></section>}{message&&<Alert kind={success?'success':'error'}>{message}</Alert>}</>
}

function PilotPrivateFile({path}:{path:string}){const[url,setUrl]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');const load=useCallback(async()=>{setLoading(true);setError('');const result=await supabase.storage.from('evidence').createSignedUrl(path,300);if(result.error||!result.data?.signedUrl)setError('Não foi possível abrir o arquivo privado.');else setUrl(result.data.signedUrl);setLoading(false)},[path]);useEffect(()=>{load()},[load]);return loading?<span>Preparando arquivo privado…</span>:error?<span className="inline-error">{error} <button onClick={load}>Tentar novamente</button></span>:<a className="file-link" href={url} target="_blank">Abrir arquivo privado (5 min)</a>}

function PilotContract({profile,contractId}:{profile:Profile;contractId?:string}){
 const[c,setC]=useState<any>(null),[acceptances,setAcceptances]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[success,setSuccess]=useState(false),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{setLoading(true);setError('');let query=supabase.from('conquest_contracts').select('*,conquest:conquests(*),parent:profiles!conquest_contracts_parent_id_fkey(first_name,last_name),youth:profiles!conquest_contracts_youth_id_fkey(first_name,last_name)');query=contractId?query.eq('id',contractId):query.order('created_at',{ascending:false}).limit(1);const result=await query.maybeSingle();if(result.error||(!result.data&&contractId)){setError(contractId?'Combinado não encontrado ou sem permissão para esta família.':'Não conseguimos carregar o combinado.');setLoading(false);return}if(!result.data){setC(null);setLoading(false);return}const acceptanceResult=await supabase.from('contract_acceptances').select('role,accepted_at').eq('contract_id',result.data.id);if(acceptanceResult.error){setError('Não conseguimos carregar os aceites do combinado.');setLoading(false);return}setC(result.data);setAcceptances(acceptanceResult.data||[]);if(!contractId)history.replaceState(null,'',appRouteUrl({view:'contract',contractId:result.data.id}));setLoading(false)},[contractId]);useEffect(()=>{load()},[load]);
 const accept=async()=>{if(!c)return;setBusy(true);setMessage('');setSuccess(false);const{data,error:failure}=await supabase.rpc('accept_commitment',{target_contract:c.id});setBusy(false);if(failure)return setMessage(friendlyError(failure,'Não foi possível registrar seu aceite. Tente novamente.'));setSuccess(true);setMessage(data==='ACTIVE'?'Combinado aceito por todos. As missões estão liberadas.':'Sua confirmação foi registrada. Falta a outra pessoa aceitar.');load()};
 if(loading)return <LoadingState label="Carregando combinado…"/>;if(error)return <RetryState message={error} onRetry={load}/>;if(!c)return <><Header over="ACORDO" title="Compromisso" text="Ele aparece depois que o responsável revisa e aprova a jornada."/><section className="empty-card"><p>Nenhum compromisso disponível.</p></section></>;const accepted=acceptances.some(a=>a.role===profile.role),parentAccepted=acceptances.some(a=>a.role==='PARENT'),youthAccepted=acceptances.some(a=>a.role==='YOUTH');return <><Header over="COMPROMISSO DA CONQUISTA" title={c.conquest.title} text="Um combinado mútuo entre jovem e responsável. Não é um contrato jurídico."/><section className="panel contract-card"><span className="status-pill">{c.status==='ACTIVE'?'ATIVO':'AGUARDANDO ACEITES'}</span><div className="status-line"><span>Objetivo</span><b>{c.conquest.title}</b></div><div className="status-line"><span>Prazo combinado</span><b>{c.conquest.desired_date?new Date(`${c.conquest.desired_date}T12:00:00`).toLocaleDateString('pt-BR'):'Sem prazo definido'}</b></div>{c.conquest.confirmed_goal_value&&<div className="status-line"><span>Valor confirmado</span><b>{moneyBRL(Number(c.conquest.confirmed_goal_value))}</b></div>}<div className="status-line"><span>Jornada inicial</span><b>{c.estimated_missions} missões</b></div><div className="status-line"><span>{c.parent?.first_name||'Responsável'}</span><b>{parentAccepted?'Aceitou':'Pendente'}</b></div><div className="status-line"><span>{c.youth?.first_name||'Jovem'}</span><b>{youthAccepted?'Aceitou':'Pendente'}</b></div><blockquote>{c.conquest.reward_agreement||c.conditions}</blockquote>{!accepted&&<button className="primary" disabled={busy} onClick={accept}>{busy?'Registrando…':'Li e aceito este combinado'}</button>}{accepted&&c.status!=='ACTIVE'&&<Alert kind="success">Sua confirmação está registrada. A jornada começa quando a outra pessoa aceitar.</Alert>}</section>{message&&<Alert kind={success?'success':'error'}>{message}</Alert>}</>
}

function PilotNotifications({go}:{go:Go}){const[items,setItems]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState('');const load=useCallback(async()=>{setLoading(true);setError('');const result=await supabase.from('notifications').select('*').order('created_at',{ascending:false}).limit(30);if(result.error)setError('Não conseguimos carregar suas notificações.');else setItems(result.data||[]);setLoading(false)},[]);useEffect(()=>{load()},[load]);const open=async(n:any)=>{setMessage('');if(!n.read_at){const read=await supabase.rpc('mark_notification_read',{target_notification:n.id});if(read.error)return setMessage('Não foi possível marcar a notificação como lida. Tente novamente.')}const target=notificationRoute(n);go(target.view,{assignmentId:target.assignmentId,contractId:target.contractId})};return <><Header over="CENTRAL" title="Notificações" text="O que pede atenção e o que já avançou."/>{loading?<LoadingState label="Carregando notificações…"/>:error?<RetryState message={error} onRetry={load}/>:items.length?<div className="notification-list">{items.map(n=><button key={n.id} className={n.read_at?'read':''} onClick={()=>open(n)}><i/><span><b>{n.title}</b><small>{n.message}</small></span></button>)}</div>:<section className="empty-card"><p>Nenhuma notificação por aqui.</p></section>}{message&&<Alert>{message}</Alert>}</>}

function Passport({profile}:{profile:Profile}){const[xp,setXp]=useState(0),[done,setDone]=useState<any[]>([]);useEffect(()=>{supabase.from('youth_profiles').select('total_xp').eq('profile_id',profile.id).maybeSingle().then(({data})=>setXp(data?.total_xp||0));supabase.from('mission_assignments').select('approved_at,mission:missions(title,skills)').eq('status','APPROVED').order('approved_at',{ascending:false}).then(({data})=>setDone(data||[]))},[profile.id]);const all=useMemo(()=>done.flatMap(x=>(x.mission as any).skills||[]),[done]);return <><Header over="SUA HISTÓRIA" title="Passaporte" text="Evidências reais do que você já colocou em prática."/><section className="passport-head"><div className="passport-avatar">{profile.first_name[0]}</div><div><h2>{profile.first_name}</h2><p>{xp} XP · {done.length} missões verificadas</p></div><Mark/></section><h2 className="subheading">Habilidades praticadas</h2><div className="choice-grid">{[...new Set(all)].map(x=><span className="skill-chip" key={x}>{x}</span>)}</div><h2 className="subheading">Trajetória</h2>{done.map((x:any)=><div className="timeline-item" key={x.approved_at}><i>✓</i><span><b>{x.mission.title}</b><small>{new Date(x.approved_at).toLocaleDateString('pt-BR')}</small></span></div>)}</>}
function ParentInvite({family}:{family:Family}){const[token,setToken]=useState(''),[code,setCode]=useState(family.invite_code),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);useEffect(()=>{supabase.from('family_invites').select('link_token,code').eq('family_id',family.id).is('claimed_at',null).order('created_at',{ascending:false}).limit(1).maybeSingle().then(({data})=>{setToken(data?.link_token||'');setCode(data?.code||family.invite_code)})},[family.id,family.invite_code]);const link=token&&typeof location!=='undefined'?`${location.origin}/invite/${token}`:'';const copy=async(value:string,label:string)=>{await navigator.clipboard.writeText(value);setMessage(label)};const create=async()=>{setBusy(true);setMessage('');const{data}=await supabase.auth.getSession();const response=await fetch('/api/auth/family-invites',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${data.session?.access_token}`},body:JSON.stringify({familyId:family.id})}),body=await response.json() as{error?:string;linkToken?:string;code?:string};setBusy(false);if(!response.ok||!body.linkToken)return setMessage(body.error||'Não foi possível criar o convite.');setToken(body.linkToken);setCode(body.code||'');setMessage('Novo convite criado.')};const share=async()=>{if(!link)return;if(navigator.share){try{await navigator.share({title:'Convite KONKI',text:'Entre na nossa família na KONKI.',url:link});setMessage('Convite compartilhado.');return}catch{}}await copy(link,'Link copiado.')};return <section className="panel invite-panel"><h2>Convide alguém da família</h2><p>O convidado escolhe se entra como responsável ou jovem. Cada link pode ser usado uma vez.</p>{link?<div className="action-row"><button className="primary" onClick={()=>copy(link,'Link copiado.')}>Copiar link</button><button className="secondary" onClick={share}>Compartilhar</button></div>:<Alert>O último convite já foi usado. Gere outro para adicionar uma pessoa.</Alert>}<button className="secondary wide" disabled={busy} onClick={create}>{busy?'Gerando…':link?'Gerar outro convite':'Gerar novo convite'}</button>{code&&<div className="invite"><span>Ou use o código para jovem</span><button onClick={()=>copy(code,'Código copiado.')}><b>{code}</b></button></div>}{message&&<Alert kind={message.includes('criado')||message.includes('copiado')||message.includes('compartilhado')?'success':'error'}>{message}</Alert>}</section>}
function ProfileScreen({profile,family,logout}:{profile:Profile;family:Family|null;logout:()=>void}){return <><Header over="SUA CONTA" title={profile.first_name} text={`${roleLabel(profile.role)} · ${family?.name||'KONKI'}`}/>{profile.role==='PARENT'&&family&&<ParentInvite family={family}/>}<ThemeControl/><section className="panel"><h2>Privacidade</h2><p>Seus dados, conquistas e evidências são privados e isolados por família.</p><button className="secondary wide" onClick={logout}>Sair</button></section></>}
function Admin(){const[data,setData]=useState<any>(null),[error,setError]=useState('');useEffect(()=>{supabase.auth.getSession().then(async({data:s})=>{const r=await fetch('/api/admin/overview',{headers:{authorization:`Bearer ${s.session?.access_token}`}});const j=await r.json() as ApiResponse;if(r.ok)setData(j);else setError(j.error||'Não foi possível carregar a visão administrativa.')})},[]);return <><Header over="ADMIN" title="Operação KONKI" text="Métricas agregadas sem expor evidências privadas."/>{error&&<Alert>{error}</Alert>}{data&&<><div className="admin-grid">{Object.entries(data.metrics||{}).map(([k,v])=><div key={k}><b>{String(v)}</b><small>{k.replaceAll('_',' ')}</small></div>)}</div><section className="panel"><h2>Funil</h2>{Object.entries(data.funnel||{}).map(([k,v])=><div className="status-line" key={k}><span>{k}</span><b>{String(v)}</b></div>)}</section></>}</>}
function Header({over,title,text}:{over:string;title:string;text:string}){return <header className="page-title"><span>{over}</span><h1>{title}</h1><p>{text}</p></header>}
function Nav({role,active,go}:{role:Role;active:View;go:(v:View)=>void}){const items:[View,string,string][] = role==='PARENT'?[['home','Início','⌂'],['conquest','Conquista','◇'],['review','Revisar','✓'],['contract','Contrato','▤'],['profile','Perfil','○']]:[['home','Início','⌂'],['missions','Missões','✓'],['conquest','Conquista','◇'],['passport','Passaporte','▤'],['profile','Perfil','○']];return <nav className="bottom-nav">{items.map(([v,l,i])=><button key={v} className={active===v?'active':''} onClick={()=>go(v)}><i>{i}</i><span>{l}</span></button>)}</nav>}
