const normalized=(value?:string|null)=>String(value||'').trim().toUpperCase().replaceAll('-','_').replaceAll(' ','_');

const status:Record<string,string>={DRAFT:'Rascunho',PENDING:'Pendente',PENDING_REVIEW:'Aguardando revisão',CHANGES_REQUESTED:'Ajustes solicitados',APPROVED:'Aprovada',ACTIVE:'Ativa',COMPLETED:'Concluída',ARCHIVED:'Encerrada',CANCELLED:'Cancelada',LOCKED:'Bloqueada',AVAILABLE:'Disponível',STARTED:'Em andamento',SUBMITTED:'Aguardando revisão',NEEDS_CHANGES:'Precisa de ajuste',SAVED:'Guardada'};
const evidence:Record<string,string>={TEXT:'Texto',IMAGE:'Foto',AUDIO:'Áudio',LINK:'Link'};
const role:Record<string,string>={PARENT:'Responsável',YOUTH:'Jovem',ADMIN:'Administrador'};
const skillAliases:Record<string,string>={FINANCIAL_EDUCATION:'FINANCIAL_LITERACY',EDUCAÇÃO_FINANCEIRA:'FINANCIAL_LITERACY',FINANCIAL_LITERACY:'FINANCIAL_LITERACY',DECISION_MAKING:'DECISION_MAKING',TOMADA_DE_DECISÃO:'DECISION_MAKING',CRITICAL_THINKING:'CRITICAL_THINKING',PENSAMENTO_CRÍTICO:'CRITICAL_THINKING',PROBLEM_SOLVING:'PROBLEM_SOLVING',RESOLUÇÃO_DE_PROBLEMAS:'PROBLEM_SOLVING',TIME_MANAGEMENT:'TIME_MANAGEMENT',GESTÃO_DO_TEMPO:'TIME_MANAGEMENT',SELF_KNOWLEDGE:'SELF_KNOWLEDGE',AUTOCONHECIMENTO:'SELF_KNOWLEDGE',ENTREPRENEURSHIP:'ENTREPRENEURSHIP',EMPREENDEDORISMO:'ENTREPRENEURSHIP',AUTONOMY:'AUTONOMY',AUTONOMIA:'AUTONOMY',COMMUNICATION:'COMMUNICATION',COMUNICAÇÃO:'COMMUNICATION',DISCIPLINE:'DISCIPLINE',DISCIPLINA:'DISCIPLINE',ORGANIZATION:'ORGANIZATION',ORGANIZAÇÃO:'ORGANIZATION',RESPONSIBILITY:'RESPONSIBILITY',RESPONSABILIDADE:'RESPONSIBILITY',INITIATIVE:'INITIATIVE',INICIATIVA:'INITIATIVE',NEGOTIATION:'NEGOTIATION',NEGOCIAÇÃO:'NEGOTIATION',CREATIVITY:'CREATIVITY',CRIATIVIDADE:'CREATIVITY',TECHNOLOGY:'TECHNOLOGY',TECNOLOGIA:'TECHNOLOGY'};
const skill:Record<string,string>={FINANCIAL_LITERACY:'Educação financeira',DECISION_MAKING:'Tomada de decisão',CRITICAL_THINKING:'Pensamento crítico',PROBLEM_SOLVING:'Resolução de problemas',TIME_MANAGEMENT:'Gestão do tempo',SELF_KNOWLEDGE:'Autoconhecimento',ENTREPRENEURSHIP:'Empreendedorismo',AUTONOMY:'Autonomia',COMMUNICATION:'Comunicação',DISCIPLINE:'Disciplina',ORGANIZATION:'Organização',RESPONSIBILITY:'Responsabilidade',INITIATIVE:'Iniciativa',NEGOTIATION:'Negociação',CREATIVITY:'Criatividade',TECHNOLOGY:'Tecnologia'};

export const statusLabel=(value?:string|null)=>status[normalized(value)]||value||'Não informado';
export const evidenceLabel=(value?:string|null)=>evidence[normalized(value)]||value||'Não informado';
export const roleLabel=(value?:string|null)=>role[normalized(value)]||value||'Não informado';
export const canonicalSkill=(value?:string|null)=>skillAliases[normalized(value)]||normalized(value);
export const skillLabel=(value?:string|null)=>skill[canonicalSkill(value)]||value||'Não informado';
export const canonicalSkills=(values:(string|null|undefined)[]=[])=>[...new Map(values.filter(Boolean).map(value=>{const id=canonicalSkill(value);return[id,skill[id]||String(value)]})).entries()].map(([id,label])=>({id,label}));
