import{performance}from'node:perf_hooks';import{readFileSync}from'node:fs';import{MISSION_SYSTEM_VERSION}from'./types.mjs';import{MISSION_CONTRACTS}from'../../data/mission-system-v1/mission-contracts.mjs';import{composeJourney}from'./journey-composer.mjs';import{materializeMission}from'./mission-materializer.mjs';import{adaptProductContext,sanitizeLegacyResult}from'./product-context-adapter.mjs';import{compareLegacyV1}from'./shadow-comparison.mjs';import{recordShadowAudit}from'./shadow-observability.mjs';
const controlledModes=new Set(['OFF','SHADOW']),manualPlan=JSON.parse(readFileSync(new URL('../../docs/mission-system-v1/manual-review-operational-plan.json',import.meta.url),'utf8'));
export function resolveMissionSystemMode(value=process.env.MISSION_SYSTEM_V1_MODE){return controlledModes.has(value)?value:'OFF'}
const safeError=(code,message)=>({code,safeMessage:String(message||'Shadow execution failed').slice(0,160).replace(/[\w.+-]+@[\w.-]+/g,'[redacted]')});
const variablesFor=(missionId,context)=>{const contract=MISSION_CONTRACTS[missionId],variables={};if(contract?.allowedVariables.some(x=>x.name==='goal_name')&&context.goal.title)variables.goal_name={value:context.goal.title,source:'GOAL_STATE',provenance:'product_context_adapter'};return variables};
const missionIdsIn=text=>{const ids=new Set([...String(text).matchAll(/M(\d{2})(?:[–-]M(\d{2}))?/g)].flatMap(match=>{const start=Number(match[1]),end=Number(match[2]||match[1]);return Array.from({length:end-start+1},(_,i)=>`M${String(start+i).padStart(2,'0')}`)}));return ids};
const manualFlagsFor=(composition,context)=>{const ids=(composition.missions||[]).map(x=>x.missionId),contracts=ids.map(id=>MISSION_CONTRACTS[id]).filter(Boolean);return manualPlan.rules.filter(rule=>{const referenced=missionIdsIn(rule.trigger);if(referenced.size&&ids.some(id=>referenced.has(id)))return true;if(rule.rule===14)return contracts.some((item,index)=>index>0&&item.noveltyGroup==='SOCIAL_CONVERSATION'&&contracts[index-1].noveltyGroup==='SOCIAL_CONVERSATION');if([39,69].includes(rule.rule))return context.youth.interests.length>0;if(rule.rule===66)return ids.includes('M27')&&ids.includes('M28');if(rule.rule===111)return ids.filter(id=>['M38','M39','M42'].includes(id)).length>1;return false}).map(rule=>({ruleId:rule.rule,trigger:rule.trigger,reviewOwner:rule.reviewOwner,enforcement:rule.enforcement,evidenceAvailable:['normalized_context','eligibility_reasons','selected_mission_contract','canonical_content_version','sequence_signature']}))};
const blockedAlternatives=evaluations=>{const seen=new Set(),items=[];for(const item of evaluations||[]){const e=item.eligibility;if(!e||e.status==='ELIGIBLE'||seen.has(item.missionId))continue;seen.add(item.missionId);const catalogReason=(e.reasons||[]).find(x=>String(x).startsWith('Catálogo obrigatório'));items.push({missionId:item.missionId,status:e.status,hardFilter:e.hardFilter||null,resultCode:e.resultCode||null,reasons:(e.reasons||[]).slice(0,3),catalogGap:catalogReason?{catalogId:String(catalogReason).split(': ').at(-1),missionId:item.missionId,missingCoverage:'required catalog unavailable for current shadow context'}:null})}return items};
async function executeShadow({adapted,legacy,compose=composeJourney,materialize=materializeMission}){const composition=compose(adapted.context),selected=composition.missions?.[0]||null,contract=selected?MISSION_CONTRACTS[selected.missionId]:null;let materializationStatus=null,resultCode=composition.code;if(selected){const materialized=materialize(selected.missionId,variablesFor(selected.missionId,adapted.context),{youthAge:adapted.context.youth.age,goalType:adapted.context.goal.primaryGoalType});materializationStatus=materialized.code;if(materialized.code!=='MISSION_SELECTED')resultCode=materialized.code}const evaluations=composition.evaluations||[],selectedEvaluation=[...evaluations].reverse().find(x=>x.missionId===selected?.missionId),manualReviewFlags=manualFlagsFor(composition,adapted.context),v1={compositionResultCode:composition.code,resultCode,missionId:selected?.missionId||null,journeyRole:selectedEvaluation?.eligibility?.role||null,score:selected?.score??null,eligibilityReasons:selectedEvaluation?.eligibility?.reasons||composition.reasons||[],blockedAlternatives:blockedAlternatives(evaluations),materializationStatus,manualReviewFlags,semantic:contract?{mechanic:contract.mechanic,experiencePattern:contract.experiencePattern,goalType:adapted.context.goal.primaryGoalType,journeyRole:selectedEvaluation?.eligibility?.role||null}:null};return{v1,comparison:compareLegacyV1(legacy,v1)}}
export async function runMissionSystemShadow({mode=resolveMissionSystemMode(),productContext={},legacyResult={},timeoutMs=50,auditSink=recordShadowAudit,dependencies={}}={}){
  if(mode!=='SHADOW')return{mode:'OFF',executed:false,audit:null};
  const start=performance.now(),legacy=sanitizeLegacyResult(legacyResult),adapted=adaptProductContext(productContext);let result,error=null;
  try{const work=(dependencies.execute||executeShadow)({adapted,legacy,compose:dependencies.compose||composeJourney,materialize:dependencies.materialize||materializeMission}),timeout=new Promise((_,reject)=>setTimeout(()=>reject(new Error('SHADOW_TIMEOUT')),timeoutMs));result=await Promise.race([work,timeout])}catch(caught){const message=caught instanceof Error?caught.message:'SHADOW_UNEXPECTED_ERROR';error=safeError(message==='SHADOW_TIMEOUT'?'TIMEOUT':'V1_EXCEPTION',message);result={v1:{compositionResultCode:null,resultCode:'V1_ERROR',missionId:null,journeyRole:null,score:null,eligibilityReasons:[],blockedAlternatives:[],materializationStatus:null,manualReviewFlags:[],semantic:null},comparison:{result:'V1_ERROR',reasons:[error.code]}}}
  const audit={timestamp:new Date().toISOString(),missionSystemVersion:MISSION_SYSTEM_VERSION,contextFingerprint:adapted.contextFingerprint,sanitizedContextSummary:adapted.sanitizedContextSummary,legacy,v1:result.v1,comparison:result.comparison,performance:{durationMs:+(performance.now()-start).toFixed(4)},error};
  try{auditSink?.(audit)}catch{}
  return{mode:'SHADOW',executed:true,audit};
}
