alter table public.youth_profiles add column if not exists birth_date date;
alter table public.conquests add column if not exists normalized_goal text, add column if not exists natural_reference text, add column if not exists goal_type text, add column if not exists goal_category text, add column if not exists estimated_market_value numeric(12,2), add column if not exists classification jsonb not null default '{}'::jsonb;
alter table public.journeys add column if not exists complexity_score numeric(6,3), add column if not exists complexity_band text, add column if not exists suggested_duration_weeks integer;
alter table public.journey_missions add column if not exists archetype_id uuid, add column if not exists contextualized_intro text, add column if not exists contextualized_micro_lesson text, add column if not exists contextualized_steps jsonb not null default '[]'::jsonb, add column if not exists contextualized_evidence_request text, add column if not exists follow_up_question text, add column if not exists why_this_mission text, add column if not exists effort_weight integer not null default 2 check(effort_weight between 1 and 5), add column if not exists progress_percentage numeric(8,4) not null default 0;
alter table public.missions alter column goal_progress_reward type numeric(8,4);
alter table public.conquests alter column progress type numeric(8,4);

create table if not exists public.mission_archetypes(
 id uuid primary key default gen_random_uuid(), code text not null unique, category text not null check(category in ('DEVELOPMENT_CONTEXTUALIZED','CONQUEST','EXPANSION')), title_template text not null, pedagogical_objective text not null, primary_skills text[] not null, secondary_skills text[] not null default '{}', age_min integer not null default 10, age_max integer not null default 18, difficulty text not null default 'MEDIUM', estimated_minutes_min integer not null, estimated_minutes_max integer not null, allowed_goal_types text[] not null default '{}', preferred_goal_categories text[] not null default '{}', when_to_use text not null, when_not_to_use text not null, base_micro_lesson text not null, base_steps jsonb not null, allowed_evidence_types text[] not null, follow_up_question_templates text[] not null, default_effort_weight integer not null check(default_effort_weight between 1 and 5), default_xp integer not null, is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
alter table public.journey_missions add constraint journey_missions_archetype_fk foreign key(archetype_id) references public.mission_archetypes(id);
alter table public.mission_archetypes enable row level security;
create policy archetypes_read on public.mission_archetypes for select to authenticated using(is_active or public.is_admin());
create policy archetypes_admin on public.mission_archetypes for all using(public.is_admin()) with check(public.is_admin());

create table if not exists public.conquest_wishlist(id uuid primary key default gen_random_uuid(),family_id uuid not null references public.families(id) on delete cascade,youth_id uuid not null references public.profiles(id) on delete cascade,title text not null,context text,category text,status text not null default 'SAVED' check(status in ('SAVED','ACTIVATED','ARCHIVED')),created_at timestamptz not null default now());
alter table public.conquest_wishlist enable row level security;
create policy wishlist_family_read on public.conquest_wishlist for select using(public.is_family_member(family_id) or public.is_admin());
create policy wishlist_youth_write on public.conquest_wishlist for all using(youth_id=auth.uid() or public.is_admin()) with check(youth_id=auth.uid() or public.is_admin());

create table if not exists public.contract_acceptances(id uuid primary key default gen_random_uuid(),contract_id uuid not null references public.conquest_contracts(id) on delete cascade,user_id uuid not null references public.profiles(id),role text not null check(role in ('PARENT','YOUTH')),contract_version text not null default '1.0',accepted_at timestamptz not null default now(),unique(contract_id,user_id,contract_version));
alter table public.contract_acceptances enable row level security;
create policy contract_acceptances_family_read on public.contract_acceptances for select using(public.is_admin() or exists(select 1 from public.conquest_contracts c where c.id=contract_id and public.is_family_member(c.family_id)));
create policy contract_acceptances_self_insert on public.contract_acceptances for insert with check(user_id=auth.uid() and exists(select 1 from public.conquest_contracts c where c.id=contract_id and (c.parent_id=auth.uid() or c.youth_id=auth.uid())));

create or replace function public.recalculate_journey_progress(target_journey uuid) returns void language plpgsql security definer set search_path=public as $$
declare total numeric;
begin
 select coalesce(sum(effort_weight),0) into total from public.journey_missions where journey_id=target_journey;
 if total>0 then update public.journey_missions set progress_percentage=round((effort_weight::numeric/total)*100,4),goal_progress_reward=round((effort_weight::numeric/total)*100,4) where journey_id=target_journey; end if;
end $$;
create or replace function public.recalculate_journey_progress_trigger() returns trigger language plpgsql security definer set search_path=public as $$ begin perform public.recalculate_journey_progress(coalesce(new.journey_id,old.journey_id));return coalesce(new,old);end $$;
drop trigger if exists journey_progress_recalc on public.journey_missions;
create trigger journey_progress_recalc after insert or delete or update of effort_weight on public.journey_missions for each row execute function public.recalculate_journey_progress_trigger();

create or replace function public.accept_commitment(target_contract uuid) returns text language plpgsql security definer set search_path=public as $$
declare c public.conquest_contracts; r text; n integer;
begin select * into c from public.conquest_contracts where id=target_contract;if c.id is null then raise exception 'not_found';end if;
if auth.uid()=c.parent_id then r:='PARENT';elsif auth.uid()=c.youth_id then r:='YOUTH';else raise exception 'not_allowed';end if;
insert into public.contract_acceptances(contract_id,user_id,role) values(c.id,auth.uid(),r) on conflict do nothing;
select count(distinct role) into n from public.contract_acceptances where contract_id=c.id and contract_version='1.0';
if n=2 then update public.conquest_contracts set status='ACTIVE',parent_accepted_at=coalesce(parent_accepted_at,now()),youth_accepted_at=coalesce(youth_accepted_at,now()) where id=c.id;update public.journeys set status='ACTIVE',updated_at=now() where conquest_id=c.conquest_id;update public.conquests set status='ACTIVE' where id=c.conquest_id;return 'ACTIVE';end if;return 'PENDING';end $$;

create or replace function public.approve_journey(target_journey uuid) returns jsonb language plpgsql security definer set search_path=public as $$
declare j public.journeys; c public.conquests; jm public.journey_missions; mid uuid; parent_id uuid; total integer;
begin select * into j from public.journeys where id=target_journey for update;if j.id is null or not public.is_family_parent(j.family_id) then raise exception 'not_allowed';end if;if j.status<>'DRAFT' then raise exception 'invalid_status';end if;
perform public.recalculate_journey_progress(j.id);select count(*) into total from public.journey_missions where journey_id=j.id;select * into c from public.conquests where id=j.conquest_id;select profile_id into parent_id from public.family_members where family_id=j.family_id and role='PARENT' order by joined_at limit 1;
for jm in select * from public.journey_missions where journey_id=j.id order by mission_order loop
 insert into public.missions(slug,title,description,category,skills,interests,goal_categories,recommended_age_min,recommended_age_max,difficulty,estimated_minutes,xp_reward,goal_progress_reward,evidence_types,lesson_title,lesson_content,status,family_id)
 values('family-'||j.family_id||'-'||jm.id,jm.title,coalesce(jm.contextualized_intro,jm.description),jm.category,jm.skills,'{}',array[c.category],8,21,'MEDIUM',jm.estimated_minutes,jm.xp_reward,jm.progress_percentage,jm.evidence_types,'Antes de começar',jsonb_build_object('contexto',jm.contextualized_intro,'microaula',jm.contextualized_micro_lesson,'passos',jm.contextualized_steps,'prova',jm.contextualized_evidence_request,'follow_up',jm.follow_up_question),'ACTIVE',j.family_id) returning id into mid;
 insert into public.mission_assignments(family_id,youth_id,conquest_id,mission_id,assigned_by,recommendation_score,recommendation_reasons,status) values(j.family_id,j.youth_id,j.conquest_id,mid,auth.uid(),jm.recommendation_score,array[jm.why_this_mission],'AVAILABLE');
end loop;
update public.journeys set status='APPROVED',approved_by=auth.uid(),approved_at=now(),updated_at=now() where id=j.id;update public.conquests set status='APPROVED',approved_at=now(),recommended_mission_count=total where id=j.conquest_id;
insert into public.conquest_contracts(conquest_id,family_id,parent_id,youth_id,estimated_missions,conditions,status) values(j.conquest_id,j.family_id,parent_id,j.youth_id,total,'Cumprir o combinado quando a jornada for concluída nas condições acordadas.','PENDING') on conflict(conquest_id) do update set estimated_missions=excluded.estimated_missions,conditions=excluded.conditions,status='PENDING',parent_accepted_at=null,youth_accepted_at=null;
insert into public.notifications(recipient_id,family_id,type,title,message,related_entity_id,deep_link) values(j.youth_id,j.family_id,'COMMITMENT_READY','Sua jornada foi aprovada.','Confirme o combinado para liberar as missões.',j.id,'/?view=contract');return jsonb_build_object('status','APPROVED','mission_count',total);end $$;

create or replace function public.archive_journey(target_journey uuid, archive_reason text default null) returns void language plpgsql security definer set search_path=public as $$
declare j public.journeys;begin select * into j from public.journeys where id=target_journey;if j.id is null or not(j.youth_id=auth.uid() or public.is_family_parent(j.family_id)) then raise exception 'not_allowed';end if;update public.journeys set status='ARCHIVED',updated_at=now() where id=j.id;update public.conquests set status='ARCHIVED' where id=j.conquest_id;update public.mission_assignments set status='CANCELLED' where conquest_id=j.conquest_id and status in ('AVAILABLE','STARTED','NEEDS_CHANGES');insert into public.analytics_events(family_id,user_id,event_name,properties) values(j.family_id,auth.uid(),'journey_archived',jsonb_build_object('reason',archive_reason));end $$;

grant all on public.mission_archetypes,public.conquest_wishlist,public.contract_acceptances to service_role;
grant select on public.mission_archetypes to authenticated;
grant select,insert,update,delete on public.conquest_wishlist to authenticated;
grant select,insert on public.contract_acceptances to authenticated;
grant execute on function public.recalculate_journey_progress(uuid),public.accept_commitment(uuid),public.archive_journey(uuid,text) to authenticated,service_role;

insert into public.mission_archetypes(code,category,title_template,pedagogical_objective,primary_skills,secondary_skills,estimated_minutes_min,estimated_minutes_max,allowed_goal_types,preferred_goal_categories,when_to_use,when_not_to_use,base_micro_lesson,base_steps,allowed_evidence_types,follow_up_question_templates,default_effort_weight,default_xp)
select code,category,title,objective,skills,secondary,minutes,greatest(minutes+15,30),goal_types,categories,'Quando a atividade tem relação concreta com a conquista.','Quando a relação exigir uma justificativa artificial.',lesson,jsonb_build_array('Entenda o desafio.','Faça usando dados reais.','Registre sua decisão e o que aprendeu.'),evidence,array['O que faria você mudar sua decisão?','Qual foi a parte mais importante do seu raciocínio?'],weight,xp from (values
('DC01','DEVELOPMENT_CONTEXTUALIZED','Compare alternativas','Ensinar comparação racional usando múltiplos critérios.',array['critical_thinking','decision_making'],array['financial_literacy'],30,array['physical_product','travel','experience','project'],array['fashion','technology','travel'],'Use uma matriz simples: critérios nas linhas, opções nas colunas e dados reais em cada célula.',array['TEXT','IMAGE','LINK'],2,180),
('DC02','DEVELOPMENT_CONTEXTUALIZED','Defenda sua decisão','Ensinar argumentação estruturada usando tese, evidência e conclusão.',array['communication','critical_thinking'],array['decision_making'],20,array['physical_product','travel','experience','project','skill'],array[]::text[],'Uma boa defesa separa opinião de evidência e termina com uma conclusão clara.',array['TEXT','AUDIO'],2,150),
('DC03','DEVELOPMENT_CONTEXTUALIZED','Converse com quem entende','Ensinar a buscar conhecimento por perguntas boas e conversa segura.',array['communication','autonomy'],array['critical_thinking'],30,array['physical_product','travel','skill','project','career'],array[]::text[],'Perguntas abertas revelam experiência. Prepare, escute e registre o que mudou.',array['TEXT','AUDIO'],3,200),
('DC04','DEVELOPMENT_CONTEXTUALIZED','Tente uma negociação','Ensinar negociação como acordo e troca de valor, sem manipulação.',array['communication','autonomy'],array['financial_literacy'],30,array['physical_product','travel','experience','project'],array[]::text[],'Negociar é entender limites, interesses e possibilidades para construir um acordo.',array['TEXT','AUDIO'],3,220),
('DC05','DEVELOPMENT_CONTEXTUALIZED','Resolva primeiro sozinho','Desenvolver autonomia antes de pedir resposta pronta.',array['autonomy'],array['critical_thinking'],25,array['physical_product','travel','experience','skill','project','sport'],array[]::text[],'Use três passos: definir o problema, testar duas saídas e só então pedir ajuda específica.',array['TEXT','IMAGE'],2,160),
('DC06','DEVELOPMENT_CONTEXTUALIZED','Transforme a conquista em plano','Ensinar planejamento reverso e quebra do objetivo em etapas.',array['organization','autonomy'],array['discipline'],30,array['physical_product','travel','experience','skill','project','financial_goal'],array[]::text[],'Planejamento reverso começa no resultado e volta até o primeiro passo possível hoje.',array['TEXT','IMAGE'],3,200),
('DC07','DEVELOPMENT_CONTEXTUALIZED','Organize seu tempo','Ensinar organização real com blocos de tempo.',array['organization','discipline'],array['autonomy'],20,array['travel','experience','skill','project','sport','career'],array[]::text[],'Time blocking reserva um horário real para uma ação específica, com começo e fim.',array['TEXT','IMAGE'],2,150),
('DC08','DEVELOPMENT_CONTEXTUALIZED','Decida com critérios','Ensinar trade-offs e ponderação de critérios.',array['decision_making','critical_thinking'],array['financial_literacy'],30,array['physical_product','travel','experience','project','career'],array[]::text[],'Trade-off é reconhecer que ganhar em um critério pode exigir abrir mão de outro.',array['TEXT','IMAGE'],3,200),
('DC09','DEVELOPMENT_CONTEXTUALIZED','Ensine alguém','Consolidar aprendizado usando Técnica de Feynman.',array['communication'],array['critical_thinking'],25,array['physical_product','travel','skill','project','sport'],array[]::text[],'Explique com palavras simples, perceba onde travou e volte para preencher a lacuna.',array['AUDIO','TEXT'],3,200),
('DC10','DEVELOPMENT_CONTEXTUALIZED','Peça feedback específico','Ensinar como obter feedback útil e decidir o que fazer com ele.',array['communication','autonomy'],array['critical_thinking'],20,array['skill','project','career','sport','experience'],array[]::text[],'Feedback útil responde a uma pergunta concreta. Peça um exemplo e escolha uma melhoria.',array['TEXT','AUDIO'],2,160),
('DC11','DEVELOPMENT_CONTEXTUALIZED','Encontre a pergunta que falta','Descobrir a informação que ainda falta antes de decidir.',array['critical_thinking'],array['decision_making'],20,array['physical_product','travel','experience','project'],array[]::text[],'Uma decisão melhora quando você identifica qual informação mudaria sua escolha.',array['TEXT'],2,150),
('DC12','DEVELOPMENT_CONTEXTUALIZED','Aprenda uma habilidade útil','Aprender uma habilidade pequena e imediatamente aplicável.',array['autonomy','discipline'],array['organization'],45,array['travel','skill','project','sport','career'],array[]::text[],'Escolha uma habilidade pequena, pratique uma vez e use imediatamente na jornada.',array['IMAGE','AUDIO','TEXT'],3,230),
('DC13','DEVELOPMENT_CONTEXTUALIZED','Crie em vez de só consumir','Produzir um artefato real.',array['autonomy','entrepreneurship'],array['communication'],45,array['travel','experience','skill','project','career'],array[]::text[],'Criar transforma pesquisa em algo verificável que outra pessoa consegue usar.',array['IMAGE','LINK'],4,260),
('DC14','DEVELOPMENT_CONTEXTUALIZED','Crie valor e ofereça','Ensinar empreendedorismo e troca de valor apropriada à idade.',array['entrepreneurship','communication'],array['financial_literacy'],60,array['physical_product','travel','experience','project','financial_goal'],array[]::text[],'Valor nasce quando você resolve um problema real de forma segura e clara.',array['IMAGE','TEXT','AUDIO'],4,300),
('DC15','DEVELOPMENT_CONTEXTUALIZED','Resolva um problema real','Aplicar observar, entender, pensar e testar.',array['critical_thinking','autonomy'],array['organization'],45,array['travel','skill','project','sport','career'],array[]::text[],'Use problema, hipótese, teste e ajuste. Registre o que aconteceu, não só a intenção.',array['IMAGE','TEXT'],4,260),
('DC16','DEVELOPMENT_CONTEXTUALIZED','Faça algo um pouco desconfortável','Desenvolver iniciativa e confiança com desconforto leve e seguro.',array['autonomy','communication'],array['discipline'],20,array['physical_product','travel','experience','skill','project','sport'],array[]::text[],'Desconforto produtivo é pequeno, seguro e escolhido. Defina o passo antes de começar.',array['AUDIO','TEXT'],2,170),
('DC17','DEVELOPMENT_CONTEXTUALIZED','Construa consistência','Praticar comportamento pequeno e mensurável por vários dias.',array['discipline','organization'],array['autonomy'],30,array['skill','project','sport','financial_goal'],array[]::text[],'Consistência depende de uma ação pequena, um gatilho claro e um registro simples.',array['IMAGE','TEXT'],4,280),
('DC18','DEVELOPMENT_CONTEXTUALIZED','Reavalie sua decisão','Mudar ou manter uma decisão com base em novas informações.',array['decision_making','critical_thinking'],array['autonomy'],25,array['physical_product','travel','experience','project'],array[]::text[],'Reavaliar não é voltar atrás. É comparar a decisão antiga com evidências novas.',array['TEXT','AUDIO'],2,170),
('CQ01','CONQUEST','Descubra o custo real','Encontrar faixa realista de custo e distinguir preço de custo total.',array['financial_literacy'],array['critical_thinking'],30,array['physical_product','travel','experience','financial_goal'],array[]::text[],'Preço anunciado é só uma parte. Considere extras, taxas e uma margem de segurança.',array['TEXT','IMAGE','LINK'],2,180),
('CQ02','CONQUEST','Defina a conquista exata','Transformar desejo vago em objetivo específico.',array['decision_making'],array['organization'],20,array['physical_product','travel','experience','skill','project'],array[]::text[],'Um objetivo específico descreve o que é, o que não é e como reconhecer uma boa escolha.',array['TEXT'],1,120),
('CQ03','CONQUEST','Entenda o que importa','Conhecer características relevantes antes de escolher.',array['critical_thinking'],array['decision_making'],25,array['physical_product','travel','experience','skill'],array[]::text[],'Características só importam quando mudam o uso, o custo ou a experiência.',array['TEXT','IMAGE'],2,160),
('CQ04','CONQUEST','Defina seu limite','Criar limite financeiro antes da decisão emocional.',array['financial_literacy','discipline'],array['decision_making'],20,array['physical_product','travel','experience','financial_goal'],array[]::text[],'Um limite decidido antes reduz escolhas impulsivas e deixa os critérios mais claros.',array['TEXT'],2,150),
('CQ05','CONQUEST','Encontre custos escondidos','Identificar custos adicionais e custo de propriedade.',array['financial_literacy','critical_thinking'],array['organization'],30,array['physical_product','travel','experience','project'],array[]::text[],'Custo total inclui manutenção, acessórios, transporte, taxas e tempo.',array['TEXT','LINK'],2,180),
('CQ06','CONQUEST','Encontre um caminho melhor','Buscar maneiras legítimas de chegar à conquista com melhor custo-benefício.',array['autonomy','financial_literacy'],array['critical_thinking'],30,array['physical_product','travel','experience','financial_goal'],array[]::text[],'Melhor caminho equilibra preço, segurança, prazo e qualidade. Mais barato nem sempre vence.',array['TEXT','LINK'],3,200),
('CQ07','CONQUEST','Faça sua contribuição','Participar concretamente da conquista sem contribuição financeira obrigatória.',array['responsibility','autonomy'],array['discipline'],45,array['physical_product','travel','experience','project'],array[]::text[],'Contribuição pode ser pesquisa, organização, cuidado, prática ou criação de valor.',array['IMAGE','TEXT'],4,260),
('CQ08','CONQUEST','Mapeie a conquista','Criar marcos concretos entre hoje e a conquista.',array['organization','discipline'],array['autonomy'],30,array['physical_product','travel','experience','skill','project','financial_goal'],array[]::text[],'Marcos mostram avanço verificável. Cada marco precisa de resultado e próximo passo.',array['TEXT','IMAGE'],3,200),
('CQ09','CONQUEST','Simule antes','Testar ou prototipar antes de gastar ou executar.',array['critical_thinking','decision_making'],array['financial_literacy'],40,array['physical_product','travel','experience','project'],array[]::text[],'Simular revela custos, dificuldades e dúvidas enquanto ainda é barato ajustar.',array['IMAGE','TEXT'],3,220),
('CQ10','CONQUEST','Espere antes de decidir','Praticar autocontrole com período de espera quando fizer sentido.',array['discipline','decision_making'],array['financial_literacy'],15,array['physical_product','experience','financial_goal'],array[]::text[],'Cooling-off é um intervalo planejado para separar vontade momentânea de decisão consistente.',array['TEXT'],1,100),
('CQ11','CONQUEST','Tome a decisão final','Consolidar informações e tomar decisão consciente.',array['decision_making','critical_thinking'],array['communication'],30,array['physical_product','travel','experience','project'],array[]::text[],'Uma decisão final registra critérios, evidências, riscos e o motivo da escolha.',array['TEXT','AUDIO'],3,220),
('CQ12','CONQUEST','Prepare a conquista','Criar checklist final específico antes de chegar a 100%.',array['organization','responsibility'],array['autonomy'],25,array['physical_product','travel','experience','project'],array[]::text[],'Checklist final transforma detalhes em ações verificáveis antes da conclusão.',array['TEXT','IMAGE'],2,170),
('EX01','EXPANSION','Conheça uma profissão ligada a isso','Mostrar profissão naturalmente relacionada ao universo da conquista.',array['communication'],array['critical_thinking'],35,array['travel','skill','project','career'],array[]::text[],'Profissões fazem sentido quando participam diretamente da criação ou entrega da conquista.',array['TEXT','AUDIO'],2,170),
('EX02','EXPANSION','Converse com outra geração','Criar perspectiva por conversa com adulto conhecido e seguro.',array['communication'],array['critical_thinking'],30,array['physical_product','travel','experience','skill','project'],array[]::text[],'Experiências de outra época revelam o que mudou e o que continua importante.',array['AUDIO','TEXT'],2,170),
('EX03','EXPANSION','Entenda o sistema por trás','Ensinar cadeia de valor e pensamento sistêmico.',array['critical_thinking'],array['entrepreneurship'],40,array['physical_product','travel','experience','project'],array[]::text[],'Um sistema conecta pessoas, recursos, decisões e custos até a entrega final.',array['IMAGE','TEXT'],3,220),
('EX04','EXPANSION','Defenda o outro lado','Ensinar steelman e análise de argumentos contrários.',array['critical_thinking','communication'],array['decision_making'],25,array['physical_product','travel','experience','project'],array[]::text[],'Steelman é construir a versão mais forte da opinião contrária antes de responder.',array['TEXT','AUDIO'],2,180),
('EX05','EXPANSION','Construa um miniprojeto','Criar projeto concreto com aprendizados da jornada.',array['entrepreneurship','autonomy'],array['organization'],90,array['travel','skill','project','career'],array[]::text[],'Um miniprojeto tem resultado visível, limite pequeno e alguém que consegue avaliá-lo.',array['IMAGE','LINK','TEXT'],5,350),
('EX06','EXPANSION','Passe adiante','Transformar aprendizados reais em conselho útil.',array['communication'],array['critical_thinking'],30,array['physical_product','travel','experience','skill','project','sport'],array[]::text[],'Conselho útil inclui contexto, decisão, resultado e o que você faria diferente.',array['AUDIO','TEXT'],2,180)
) as x(code,category,title,objective,skills,secondary,minutes,goal_types,categories,lesson,evidence,weight,xp)
on conflict(code) do update set title_template=excluded.title_template,pedagogical_objective=excluded.pedagogical_objective,primary_skills=excluded.primary_skills,base_micro_lesson=excluded.base_micro_lesson,is_active=true;
